#!/usr/bin/env python
"""c10 `management_replay` family: rebuild + relabel on the current reward engine.

WHAT WAS WRONG WITH THE c8 FAMILY (all three defects reproduced, not assumed):

 1. POST-ACTION STATE. `build_replay_v2.py` applied the action to the accounting
    ledger BEFORE it rendered the prompt, so the position state the model was
    shown is the state AFTER the trade it is being asked about. Measured on the
    c8 train split: every one of the 11,660 EXIT-labelled rows shows
    `inventory: 0` - a FLAT position - so 38.5% of the corpus asked "what do you
    do with your position?" while showing no position, and the label was implied
    by the state rather than earned from it. ADD/REDUCE rows were likewise shown
    the post-trade size.

 2. WRONG BASIS. Labels came from the retired `replay_v2.0_constant_notional`
    heuristic (180 bp one-way, fixed risk budget), not from the reward engine that
    RL grades with, so SFT and RL disagreed about what "good" means.

 3. WRONG LABEL SEMANTICS. The candidate table in `grpo_reward_bridge` began
    REDUCE with HOLD, so "REDUCE" was graded as a hold-then-reduce trajectory.

This builder fixes all three at once:
 * the position state is the state at the DECISION INSTANT (pre-action), recovered
   exactly by inverting the archived accounting and CHECKED against the recorded
   post-action numbers of the next row in the episode (a 100% match is required;
   any mismatch is reported, never smoothed);
 * every candidate is valued from that SAME held state by
   `reward_engine.score_action_sequence(entry=...)`, the reward authority RL uses;
 * label = argmax over the four candidates, with per-candidate refusals counted.

HISTORY IS NOT THE AUTHORITY for the label. The recovered trajectory is used only
to place the decision in a real position; the label is recomputed from scratch.

Run:
  /home/alon/qwen27b-venv/bin/python build_management_c10.py --splits train validation examination
"""
from __future__ import annotations

import argparse, json, os, re, sys, time
from collections import Counter, defaultdict

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from reward_engine import Tape, RewardEngine, measure_depth  # noqa: E402
from reward_terms import RewardConfig  # noqa: E402
from grpo_reward_bridge import ACTION_SEQUENCE, score_decision  # noqa: E402
import cost_authority as CA  # noqa: E402

SPLIT_LEGACY = {"train": "train", "validation": "val", "examination": "test"}

TRADES = "/training/v2/canonical/renormalized_v7/trades.jsonl"
C8 = "/training/v2/candidate_sft_c8"
OUTDIR = "/training/v2/reports/mgmt_c10"

CAPITAL_SOL = 1.0
ENTRY_TRANCHE_SOL = 0.5
OW = 0.018                      # the ARCHIVED one-way cost, used ONLY to invert history
MIN_NOTIONAL_LAMPORTS = 100_000  # house tape filter (every production scorer uses it)
MAX_PX_RATIO = 50

# One cost statement for the whole corpus, generated by the single authority so no call
# site can reintroduce a hand-typed figure. See cost_authority.py.
COST_MODEL = CA.model_statement()

# c8 (ARCHIVED) prompt vocabulary - the parser must read the archive as it was written,
# and the new prompt is rendered separately (RE_MARK_NEW below).
RE_PRICE_ENTRY = re.compile(r"price_lamports_per_raw_token=([0-9.eE+-]+)")
RE_MARK = re.compile(r"mark price \(SOL per raw token\): ([0-9.eE+-]+)")
RE_MARK_NEW = re.compile(r"mark price \(lamports per raw token\): ([0-9.eE+-]+)")
RE_ENTRY = re.compile(r"entry price: ([0-9.eE+-]+)")
RE_HOLD = re.compile(r"holding time: ([0-9.]+) s")
RE_MFE = re.compile(r"max favourable so far: ([0-9.eE+-]+) bp")
RE_MAE = re.compile(r"max adverse so far: ([0-9.eE+-]+) bp")
RE_INV = re.compile(r"inventory: ([0-9.eE+-]+) raw tokens")
RE_CASH = re.compile(r"cash: ([0-9.eE+-]+) SOL")

SYSTEM = ("You are an on-chain position manager for pump.fun/pumpswap memecoins. You "
          "hold a position. Given the causal market snapshot and your position state, "
          "choose exactly one action: HOLD, ADD, REDUCE, EXIT. " + COST_MODEL +
          " Answer in the fixed format.")


def parse_c8(row):
    u = row["messages"][1]["content"]
    m = row["meta"]
    g = lambda rx: float(rx.search(u).group(1))
    return {
        "mint": m["mint"], "episode_id": m["episode_id"], "step": int(m["step"]),
        "old_action": m["action"], "t_dec": int(m["decision_time_unix_ms"]),
        "mark": g(RE_MARK), "entry_px": g(RE_ENTRY), "held_s": g(RE_HOLD),
        "mfe_bp": g(RE_MFE), "mae_bp": g(RE_MAE), "inv": g(RE_INV), "cash": g(RE_CASH),
        "split": m["split"],
    }


def load_tape(filepath, mints):
    """Per-mint fills in the ARCHIVE's order: (recv_unix_ms, tokens_raw).

    `load_canonical_tapes` orders ties by signature; `build_replay_v2` used
    lexsort((tokens_raw, t, mint)). For fills in the same millisecond the two orders
    disagree, so the archived entry fill is only reproducible under the archived
    order. Reproducing it is what allows the recorded entry price to be CHECKED
    instead of assumed.
    """
    import pyarrow.json as paj
    tbl = paj.read_json(filepath)
    d = tbl.to_pydict()
    keep = defaultdict(list)
    for i, m in enumerate(d["mint"]):
        if m in mints:
            keep[m].append(i)
    out, full = {}, {}
    for m, idxs in keep.items():
        idxs.sort(key=lambda i: (d["recv_unix_ms"][i], d["tokens_raw"][i]))
        sol_all = np.array([d["sol_lamports"][i] for i in idxs], dtype=np.int64)
        tok_all = np.array([d["tokens_raw"][i] for i in idxs], dtype=np.int64)
        tt_all = np.array([d["recv_unix_ms"][i] for i in idxs], dtype=np.int64)
        px_all = np.full(tt_all.size, np.nan)
        ok = tok_all != 0
        px_all[ok] = np.abs(sol_all[ok].astype(float)) / np.abs(tok_all[ok].astype(float))
        # the seed index must be read off the UNFILTERED archive-order series, or
        # dropping dust shifts it and the archived entry price stops reproducing
        full[m] = (tt_all, px_all)
        m_keep = np.isfinite(px_all) & (px_all > 0) & (np.abs(sol_all) >= MIN_NOTIONAL_LAMPORTS)
        if m_keep.sum() >= 5:
            med = float(np.median(px_all[m_keep]))
            m_keep &= (px_all >= med / MAX_PX_RATIO) & (px_all <= med * MAX_PX_RATIO)
        if m_keep.sum() < 2:
            continue
        ven = np.array([d["venue"][i] for i in idxs], dtype=object)
        sid = np.array([d["side"][i] for i in idxs], dtype=object)
        out[m] = Tape(m, tt_all[m_keep], sol_all[m_keep], tok_all[m_keep],
                      list(ven[m_keep]), list(sid[m_keep]))
    return out, full


def invert_archived(r):
    """Apply the ARCHIVED action + accounting rule to a pre-state. Returns the
    post-state and the answer to 'did the archived engine really do this?'."""
    qty, cash, cur, act = r["qty_pre"], r["cash_pre"], r["mark"], r["old_action"]
    if act == "ADD":
        add_qty = qty * 0.5
        spend = add_qty * cur * (1 + OW)
        if spend <= cash + 1e-12:
            cash -= spend
            qty += add_qty
    elif act == "REDUCE":
        sq = 0.5 * qty
        cash += sq * cur * (1 - OW)
        qty -= sq
    elif act == "EXIT":
        cash += qty * cur * (1 - OW)
        qty = 0.0
    return qty, cash


def render_user(r, label, held_pct):
    return (
        "Decide the next action for a position you already hold. Only causal "
        "information is shown.\n"
        f"MINT: {r['mint']}\n"
        f"DECISION TIME (unix ms): {r['t_dec']}\n"
        f"STEP: {r['step']}\n\n"
        "MARKET STATE (at decision time):\n"
        f"  venue: {r['venue']}  market: {r['market']}\n"
        f"  pool depth: {r['depth_sol']:.4g} SOL\n"
        f"  mark price (lamports per raw token): {r['mark']:.12g}\n"
        f"  mark price (SOL per raw token): {r['mark'] / 1e9:.12g}\n"
        f"  mark price (SOL per whole token): {r['mark'] * 1e6 / 1e9:.12g}\n"
        f"  {r['cost_line']}\n\n"
        "POSITION STATE (at the decision instant, before any action):\n"
        f"  entry price (lamports per raw token): {r['entry_px']:.12g}\n"
        f"  unrealized PnL: {r['upnl_bp']:.1f} bp\n"
        f"  holding time: {r['held_s']:.0f} s\n"
        f"  max favourable so far: {r['mfe_bp']:.1f} bp\n"
        f"  max adverse so far: {r['mae_bp']:.1f} bp\n"
        f"  inventory: {r['qty_pre']:.6g} raw tokens\n"
        f"  cash: {r['cash_pre']:.6g} SOL\n"
        f"  position value at mark: {r['qty_pre'] * r['mark']:.6g} SOL\n\n"
        "Choose exactly one action: HOLD, ADD, REDUCE, EXIT. Answer in the fixed "
        "format.")


def render_assistant(r, label):
    return (
        f"DECISION: {label}\n"
        f"POSITION: entry {r['entry_px']:.12g} -> mark {r['mark']:.12g} "
        f"({r['upnl_bp']:.1f} bp), held {r['held_s']:.0f}s\n"
        f"EVIDENCE: unrealized {r['upnl_bp']:.1f} bp; MFE {r['mfe_bp']:.1f} bp; "
        f"MAE {r['mae_bp']:.1f} bp; held {r['held_s']:.0f}s; "
        f"inventory {r['qty_pre']:.6g} raw tokens; cash {r['cash_pre']:.6g} SOL\n"
        "COUNTEREVIDENCE: a single observed path is one sample and may not repeat\n"
        f"INVALIDATION: {r['cost_line']}\n"
        "EVIDENCE_STATUS: complete")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--splits", nargs="+", default=["train", "validation", "examination"])
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--outdir", default=OUTDIR)
    ap.add_argument("--venue-fee-aware", action="store_true",
                    help="charge the pool fee only where it is NOT already inside "
                         "the recorded price (bonding curve), per exit_mechanics."
                         "cost_floor_bps. Off = historical uniform curve rate.")
    ap.add_argument("--widen-from", default="",
                    help="ITEM 1: directory of decision rows. Adds one held-position "
                         "episode per mint that the c8 management archive never covered, "
                         "so the management draw stops being a strict subset of the "
                         "BUY-seeded entry mints.")
    ap.add_argument("--widen-max-per-mint", type=int, default=1)
    ap.add_argument("--widen-entry-index", type=int, default=5,
                    help="enter at the Kth scored fill, not the mint's first print")
    ap.add_argument("--widen-min-depth-mult", type=float, default=2.0,
                    help="require pool depth >= this multiple of the entry tranche, so the "
                         "position can actually be exited and the candidates separate")
    ap.add_argument("--widen-hold-s", type=int, default=30,
                    help="whole seconds between the synthetic entry fill and the decision."
                         " Whole seconds is load-bearing: the prompt renders holding time in"
                         " seconds, meta stores ms, and the QA compares them for equality.")
    ap.add_argument("--align-to-entry-barrier", action="store_true",
                    help="score each management decision over the REMAINING time to the "
                         "entry family's barrier, instead of a fixed window. Fixes the "
                         "coherence defect: a fixed 300 s clock flattens positions before "
                         "the 1,800 s tail the entry edge depends on has resolved.")
    ap.add_argument("--horizon-s", type=int, default=1800,
                    help="forward accounting window per candidate. Every candidate "
                         "runs to t_dec + horizon (EXIT included: the window is set by "
                         "the decision, not by the action), so the lambda_time term "
                         "cannot be gamed by ending the episode early.")
    a = ap.parse_args()

    os.makedirs(a.outdir, exist_ok=True)
    cfg = RewardConfig(lambda_exposure=0.08884, horizon_ms=a.horizon_s * 1000)
    score_kw = {"horizon_ms": a.horizon_s * 1000}
    engine = RewardEngine(venue_fee_aware=a.venue_fee_aware)
    score_kw["engine"] = engine
    uniform_venue_fee = not a.venue_fee_aware
    report = {"splits": {}, "cost_statement": COST_MODEL,
              "horizon_s": a.horizon_s}

    for split in a.splits:
        t0 = time.time()
        rows = []
        with open(f"{C8}/{split}.jsonl", encoding="utf-8") as f:
            for line in f:
                r = json.loads(line)
                if (r.get("meta") or {}).get("family") != "management_replay":
                    continue
                rows.append(parse_c8(r))
        if a.limit:
            rows = rows[:a.limit]
        print(f"[{split}] c8 management rows: {len(rows)}")

        # ---- group into episodes and recover the PRE-ACTION state ------------
        eps = defaultdict(list)
        for r in rows:
            eps[r["episode_id"]].append(r)
        for v in eps.values():
            v.sort(key=lambda x: x["step"])
        eid_state = {}
        mismatches = 0
        for eid, seq in eps.items():
            prev = None
            for i, r in enumerate(seq):
                if r.get("_synthetic"):
                    # by construction: the entry tranche, held, no action taken yet
                    r["qty_pre"] = ENTRY_TRANCHE_SOL / r["entry_px"]
                    r["cash_pre"] = CAPITAL_SOL - ENTRY_TRANCHE_SOL
                    prev = (r["qty_pre"], r["cash_pre"])
                    continue
                if i == 0:
                    if r["step"] != 0:
                        r["_drop"] = "episode_without_step0"
                        continue
                    r["qty_pre"] = ENTRY_TRANCHE_SOL / r["entry_px"]
                    r["cash_pre"] = CAPITAL_SOL - ENTRY_TRANCHE_SOL
                else:
                    r["qty_pre"], r["cash_pre"] = prev
                q, c = invert_archived(r)
                tol = 2e-5 * max(1.0, abs(r["inv"]), abs(r["cash"])) + 2e-5
                if abs(q - r["inv"]) > tol or abs(c - r["cash"]) > tol:
                    mismatches += 1
                    r["_drop"] = "state_inversion_mismatch"
                prev = (q, c)
        print(f"[{split}] pre-action state recovered; mismatches={mismatches}")

        # ---- tapes -----------------------------------------------------------
        mints = {r["mint"] for r in rows}
        # ITEM 1: load the tape for the mints we intend to widen INTO, so the synthetic
        # re-entry is priced off the same series as everything else.
        wide_mints = set()
        if a.widen_from:
            with open(os.path.join(a.widen_from, f"{split}.jsonl"), encoding="utf-8") as f:
                for line in f:
                    er = json.loads(line)
                    em = er.get("meta") or {}
                    if em.get("family") != "decision":
                        continue
                    mi = em.get("mint") or er.get("mint")
                    if mi and mi not in mints:
                        wide_mints.add(mi)
            mints |= wide_mints
        t1 = time.time()
        tapes, full_series = load_tape(TRADES, mints)
        print(f"[{split}] tapes: {len(tapes)}/{len(mints)} mints in {time.time()-t1:.0f}s")

        drop = Counter()
        # ---- ITEM 1: one held-position episode per uncovered mint, derived from THE TAPE.
        # Why the first attempt was rejected: it took the entry clock and the decision clock
        # from CORPUS timestamps, so the holding period was not a whole number of seconds
        # (the prompt renders seconds, meta stores ms, and the QA compares them for exact
        # equality) and the entry fill could land after the decision clock. Both are
        # structural here - the entry IS the mint's first priced fill, the decision is
        # exactly HOLD_S later, and the row is emitted only if the tape extends past it.
        added = 0
        if a.widen_from:
            for mi in sorted(wide_mints):
                # THE FIX. The pipeline locates the entry fill ITSELF, as
                # np.searchsorted(full_series, seed, "right"). The previous version took
                # entry_px from the scored tape's first fill while the pipeline resolved a
                # different index - a same-millisecond dust print becomes the entry fill,
                # qty_pre was computed from another price, the reconstructed position is
                # inconsistent with the tape, and every candidate sequence collapses to the
                # same reward. That is the four-way tie (979 of 980 synthetic rows).
                # Derive the entry price, the entry clock AND qty_pre from the SAME index
                # the pipeline will use, and require that fill to be in the scored series.
                tp = tapes.get(mi)
                fs = full_series.get(mi)
                if tp is None or tp.tt.size == 0 or fs is None:
                    drop["widen_no_tape"] += 1
                    continue
                tt_all, px_all = fs
                # ENTRY QUALITY - the actual cause of the four-way tie. The mint's FIRST
                # priced fill is the thinnest moment of its curve. A tranche entered there
                # cannot be exited at ANY price, so the engine returns one constant for all
                # four actions (measured: HOLD=ADD=REDUCE=EXIT=-0.7543406491) and the label
                # becomes an arbitrary argmax. Enter at a later, liquid fill instead.
                k = min(a.widen_entry_index, tp.tt.size - 1)
                seed = int(tp.tt[k]) - 1
                jf = int(np.searchsorted(tt_all, seed, side="right"))
                if jf >= tt_all.size:
                    drop["widen_no_fill_after_seed"] += 1
                    continue
                t_ent = int(tt_all[jf])
                px_ent = float(px_all[jf])
                if not (bool(np.isfinite(px_ent)) and px_ent > 0):
                    drop["widen_bad_entry_fill"] += 1
                    continue
                if not bool(np.any(tp.tt == t_ent)):
                    drop["widen_entry_not_in_scored_series"] += 1
                    continue
                # VENUE. The management archive is entirely graduated-venue; the label
                # authority's curve path returns a CONSTANT for every action, so a
                # curve-venue synthetic row is a four-way tie by construction (measured:
                # 100% of ties are venue=pumpfun). Widen only into the venue the authority
                # actually prices. Curve-venue management needs the engine fixed first.
                v_at = str(tp.venue[k]) if k < len(tp.venue) else "unknown"
                if v_at != "pumpswap":
                    drop["widen_non_graduated_venue"] += 1
                    continue
                # and require the pool to be able to absorb the round trip at all
                d_sol = float(engine._depth(tp))
                if not (d_sol >= a.widen_min_depth_mult * ENTRY_TRANCHE_SOL):
                    drop["widen_thin_pool"] += 1
                    continue
                t_d = t_ent + a.widen_hold_s * 1000
                if int(tt_all[-1]) <= t_d:
                    drop["widen_no_forward_window"] += 1
                    continue
                # FORWARD LIQUIDITY. A decision whose forward window has no fills scores
                # every candidate identically - the label becomes an arbitrary argmax tie
                # (measured: 1,277 of 1,305 synthetic rows). Require the same minimum the
                # tape loader itself uses before a mint is priceable at all.
                m_fwd = np.logical_and(tp.tt > t_d, tp.tt <= t_d + a.horizon_s * 1000)
                n_fwd = int(np.count_nonzero(m_fwd))
                if n_fwd < 5:
                    drop["widen_no_forward_liquidity"] += 1
                    continue
                fwd_px = np.asarray(tp.px)[m_fwd]
                fwd_px = fwd_px[np.isfinite(fwd_px)]
                if fwd_px.size < 2 or float(fwd_px.max()) == float(fwd_px.min()):
                    drop["widen_flat_forward"] += 1
                    continue
                rows.append({
                    "mint": mi, "episode_id": "v2:%s:%d" % (mi, seed),
                    "step": 0, "t_dec": t_d, "entry_px": px_ent,
                    "held_s": float(a.widen_hold_s), "split": split,
                    "old_action": None, "_synthetic": True, "lead": True,
                    "qty_pre": ENTRY_TRANCHE_SOL / px_ent,
                    "cash_pre": CAPITAL_SOL - ENTRY_TRANCHE_SOL,
                })
                added += 1
            print(f"[{split}] widened: +{added} mints held {a.widen_hold_s}s "
                  f"(of {len(wide_mints)} uncovered)", flush=True)

        status = Counter()
        labels = Counter()
        mism = []
        out_path = os.path.join(a.outdir, f"{split}.jsonl")
        n_out = 0
        with open(out_path, "w", encoding="utf-8") as fo:
            for r in rows:
                if r.get("_drop"):
                    drop[r["_drop"]] += 1
                    continue
                t = tapes.get(r["mint"])
                if t is None:
                    drop["no_tape"] += 1
                    continue
                seed = int(r["episode_id"].rsplit(":", 1)[1])
                fs = full_series.get(r["mint"])
                if fs is None:
                    drop["no_tape"] += 1
                    continue
                tt_all, px_all = fs
                jf = int(np.searchsorted(tt_all, seed, side="right"))
                if jf >= tt_all.size:
                    drop["no_fill_after_seed"] += 1
                    continue
                px_entry = float(px_all[jf])
                if not np.isfinite(px_entry) or px_entry <= 0:
                    drop["bad_entry_fill"] += 1
                    continue
                if r.get("_synthetic"):
                    r["entry_px"] = px_entry          # no archive to reproduce
                elif abs(px_entry - r["entry_px"]) > 1e-4 * r["entry_px"]:
                    # The archived prompt prints the entry price to 8 significant
                    # digits, so a rounded match is expected; the failure mode this
                    # guard exists for (wrong basis / wrong fill) is off by >=1%.
                    # Rows on a different basis are dropped, never scored.
                    drop["entry_px_not_reproducible"] += 1
                    if len(mism) < 6:
                        near = [(int(tt_all[k]), float(px_all[k]))
                                for k in range(max(0, jf - 2), min(tt_all.size, jf + 4))]
                        mism.append({"mint": r["mint"], "eid": r["episode_id"],
                                     "step": r["step"], "prompt_entry_px": r["entry_px"],
                                     "tape_px_at_seed": px_entry, "seed": seed,
                                     "j": jf, "near": near})
                    continue
                t_entry = int(tt_all[jf])
                if r.get("_synthetic"):
                    # no archived prompt to read a holding time from: derive it from the
                    # same clocks the reward engine uses
                    r["held_s"] = (r["t_dec"] - t_entry) / 1000.0
                # the entry fill must also exist in the SCORED series, because the
                # engine re-derives the position from it
                ie = int(np.searchsorted(t.tt, t_entry, side="left"))
                if ie >= t.tt.size or int(t.tt[ie]) != t_entry:
                    drop["entry_fill_not_in_scored_series"] += 1
                    continue
                # EVERY state number the model sees is now read off the SAME price
                # series the label is scored against. The archived prompt rendered
                # its mark/MFE/MAE from the unfiltered series, so on rows whose
                # decision-time fill was dust the prompt showed a price the reward
                # never priced off (measured: upnl up to 1.1e10 bp).
                i_dec = int(np.searchsorted(t.tt, r["t_dec"], side="right")) - 1
                if i_dec < ie:
                    drop["no_fill_before_decision"] += 1
                    continue
                r["mark"] = float(t.px[i_dec])
                if not np.isfinite(r["mark"]) or r["mark"] <= 0:
                    drop["bad_mark"] += 1
                    continue
                seg = t.px[ie:i_dec + 1]
                seg = seg[np.isfinite(seg) & (seg > 0)]
                if seg.size == 0:
                    drop["empty_path_to_decision"] += 1
                    continue
                r["upnl_bp"] = (r["mark"] / px_entry - 1.0) * 1e4
                r["mfe_bp"] = (float(seg.max()) / px_entry - 1.0) * 1e4
                r["mae_bp"] = (float(seg.min()) / px_entry - 1.0) * 1e4
                # market structure + the ONE cost statement, from the single authority
                venue = str(t.venue[i_dec]) if 0 <= i_dec < len(t.venue) else "unknown"
                r["venue"] = venue
                r["market"] = ("bonding_curve" if CA.regime_for(venue) == "bonding_curve"
                               else "graduated_amm")
                r["depth_sol"] = float(engine._depth(t))
                clip = r["qty_pre"] * r["mark"]
                cost = CA.decompose(clip, r["depth_sol"], CA.regime_for(venue),
                                    uniform_venue_fee=uniform_venue_fee)
                r["cost_line"] = CA.line(clip, r["depth_sol"], CA.regime_for(venue),
                                         uniform_venue_fee=uniform_venue_fee)
                r["cost_bp"] = cost["round_trip_bp"]
                # COHERENCE: the entry family's edge is fat-tail capture at a 1,800 s
                # barrier. Scoring management over a fixed 300 s window taught the policy to
                # flatten at 5 minutes, cutting the very tails that carry the mean. Align the
                # management window to what is LEFT of the barrier.
                held_ms = r["t_dec"] - t_entry
                if a.align_to_entry_barrier:
                    remaining_ms = max(300_000, (a.horizon_s * 1000) - held_ms)
                else:
                    remaining_ms = a.horizon_s * 1000
                cfg_row = RewardConfig(lambda_exposure=0.08884, horizon_ms=remaining_ms)
                kw_row = dict(score_kw)
                kw_row["horizon_ms"] = remaining_ms
                r["management_horizon_ms"] = remaining_ms
                entry = {"entry_px": px_entry, "t_entry_ms": t_entry,
                         "qty_tokens": r["qty_pre"], "cash_sol": r["cash_pre"],
                         "capital_sol": CAPITAL_SOL}
                dec = score_decision(t, r["t_dec"], family="management", cfg=cfg_row,
                                     entry=entry, **kw_row)
                rewards, refused_any = {}, False
                for act, d in dec["per_action"].items():
                    status[d["status"]] += 1
                    if d["status"] == "ok":
                        rewards[act] = d["reward"]
                    else:
                        refused_any = True
                if refused_any or len(rewards) != 4:
                    drop["candidate_refused"] += 1
                    continue
                if any((v.get("violations") or []) for v in dec["per_action"].values()):
                    drop["conservation_violation"] += 1
                    continue
                best = max(("HOLD", "REDUCE", "EXIT", "ADD"), key=lambda k: rewards[k])
                top = sorted(rewards.values(), reverse=True)
                tie = abs(top[0] - top[1]) < 1e-12
                r["upnl_bp"] = (r["mark"] / r["entry_px"] - 1.0) * 1e4
                rec = {
                    # Top-level identity fields, matching the decision / utility_reasoning
                    # families. Integration tooling (frozen split enforcement, release
                    # payload, the family audit) reads these; a two-key row is a family
                    # that cannot be assembled without special-casing it.
                    "episode_id": r["episode_id"],
                    "family": "management_replay",
                    "mint": r["mint"],
                    "split": SPLIT_LEGACY[split],
                    "messages": [
                        {"role": "system", "content": SYSTEM},
                        {"role": "user", "content": render_user(r, best, 0.0)},
                        {"role": "assistant", "content": render_assistant(r, best)},
                    ],
                    "meta": {
                        # gate 2: unique by construction - (family, episode_id, step).
                        # A bare decision-point key collides: the same (mint, t_dec) can
                        # appear in two families AND, within management, in two episodes.
                        "candidate_id": "management_replay:%s:%d" % (
                            r["episode_id"], r["step"]),
                        "kind": "position_management_continuation",
                        "mint": r["mint"], "split": SPLIT_LEGACY[split], "episode_id": r["episode_id"],
                        "step": r["step"], "decision_time_unix_ms": r["t_dec"],
                        "action": best, "truth_type": "reward_engine_argmax",
                        "accounting_engine": "reward_engine.score_action_sequence(entry=)",
                        "family": "management_replay", "task": "next_action_decision",
                        "policy_supervision": True,
                        "candidates": {k: round(v, 10) for k, v in rewards.items()},
                        "label_margin": round(top[0] - top[1], 12),
                        "exact_tie": bool(tie),
                        "entry_mode": "continuation",
                        "t_entry_ms": t_entry,
                        "entry_px": px_entry,
                        "qty_tokens_at_decision": r["qty_pre"],
                        "cash_sol_at_decision": r["cash_pre"],
                        "capital_sol": CAPITAL_SOL,
                        "held_ms_at_decision": held_ms,
                        "management_horizon_ms": r["management_horizon_ms"],
                        "horizon_policy": ("remaining_to_entry_barrier" if a.align_to_entry_barrier
                                           else "fixed"),
                        "venue": r["venue"], "market": r["market"],
                        "depth_sol": r["depth_sol"],
                        "cost_authority": {
                            "regime": CA.regime_for(r["venue"]),
                            "depth_sol": r["depth_sol"],
                            "round_trip_bp": r["cost_bp"],
                            "venue_bp_per_leg": CA.decompose(
                                r["qty_pre"] * r["mark"], r["depth_sol"],
                                CA.regime_for(r["venue"]))["venue_bp_per_leg"],
                            "statement": r["cost_line"],
                            "authority": "cost_authority@venue_resolved",
                        },
                        "old_action": r["old_action"],
                        "policy_evidence": {
                            "action": {"status": "derived",
                                       "source": "reward_engine.score_action_sequence/continuation",
                                       "label": best, "task": "next_action_decision"},
                            "economic": {"status": "derived",
                                         "source": "reward_terms.reward_scalar",
                                         "risk_adjusted_reward": round(rewards[best], 10)},
                            "causal": {"status": "present",
                                       "source": "strict_prior_window",
                                       "ordering": "strict_prior"},
                        },
                        "prompt_revision": "c10.1-preaction-state+engine-label+cost-unified",
                    },
                }
                fo.write(json.dumps(rec, ensure_ascii=False) + "\n")
                n_out += 1
                labels[best] += 1
        report["splits"][split] = {
            "rows_in": len(rows), "rows_out": n_out,
            "dropped": dict(drop), "state_inversion_mismatches": mismatches,
            "label_distribution": dict(labels),
            "label_pct": {k: round(100.0 * v / max(1, n_out), 2) for k, v in labels.items()},
            "candidate_status": dict(status),
            "entry_mismatch_samples": mism,
            "seconds": round(time.time() - t0, 1),
        }
        print(f"[{split}] wrote {n_out} rows -> {out_path}")
        print(json.dumps(report["splits"][split], indent=1))

    with open(os.path.join(a.outdir, "BUILD_REPORT.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=1)
    return 0


if __name__ == "__main__":
    sys.exit(main())