"""Assemble candidate_sft_c9 from c8 + the full enrichment.

What changes:
  1. The enriched causal fields are injected into the entry prompt, immediately after the
     trader-share line and before CURVE STATE, so the existing structure is untouched.
  2. The management/exit family is DROPPED. Every one of those 30,313 rows carries
     `accounting_engine: replay_v2.0_constant_notional` -- the superseded accounting. Training a
     policy to drive exits on labels generated by retired economics would ship exactly the
     fabricated supervision the project forbids. Exit authority waits for the barrier-relabelled
     management family (c10); entry authority does not need it.
  3. Everything else is preserved byte-for-byte.

Naming discipline: the concentration fields are FLOAT shares (share of net wallet balances
accumulated from the tape), not shares of total supply. They are named `*_float_share` so the
model and the Rust side cannot misread them as supply concentration.
"""
import json
import os
import collections

SRC = '/training/v2/candidate_sft_c8'
DST = '/training/v2/candidate_sft_c9'
ENR = '/training/v2/reports/C9_ENRICHMENT_FULL.jsonl'
SPLITS = {'train': 'train.jsonl', 'validation': 'validation.jsonl', 'examination': 'examination.jsonl'}
ANCHOR = 'top1_trader_share='

enr = {}
with open(ENR, encoding='utf-8') as fh:
    for line in fh:
        r = json.loads(line)
        enr[(r['split'], r['row_index'])] = r
print(f"enrichment rows loaded: {len(enr):,}")

os.makedirs(DST, exist_ok=True)
report = {}
for split, fn in SPLITS.items():
    src = os.path.join(SRC, fn)
    if not os.path.isfile(src):
        continue
    dst = os.path.join(DST, fn)
    kept = dropped_mgmt = injected = missing_enr = 0
    fams = collections.Counter()
    with open(src, encoding='utf-8') as fh, open(dst, 'w', encoding='utf-8') as out:
        for idx, line in enumerate(fh):
            r = json.loads(line)
            m = r.get('meta') or {}
            task = m.get('task')
            fams[task] += 1
            if task != 'decision_action':
                dropped_mgmt += 1
                continue
            e = enr.get((split, idx))
            if e is None:
                missing_enr += 1
                kept += 1
                out.write(json.dumps(r, ensure_ascii=False) + '\n')
                continue
            lines = []
            for msg in (r.get('messages') or []):
                content = msg.get('content') or ''
                if msg.get('role') == 'user' and ANCHOR in content:
                    parts = content.split('\n')
                    ins = None
                    for i, ln in enumerate(parts):
                        if ln.startswith(ANCHOR):
                            ins = i + 1
                            break
                    if ins is not None:
                        mc = f"{e['mcap_sol_at_t']}" if e.get('mcap_sol_at_t') is not None else 'na'
                        block = [
                            "ENRICHED CANDIDATE STATE (strictly causal at t_dec): "
                            f"mcap_sol_at_t={mc} mcap_source={e['mcap_source']} "
                            f"holders_at_t={e['holders_at_t']} "
                            f"top1_float_share={e['top1_float_share']} "
                            f"top5_float_share={e['top5_float_share']} "
                            f"holder_hhi={e['holder_hhi']} "
                            f"bundle_slots={e['bundle_slots']} bundle_wallets={e['bundle_wallets']} "
                            f"volume_sol_at_t={e['volume_sol_at_t']} wash_ratio={e['wash_ratio']}",
                            "DEV HISTORY: "
                            + (f"creator_past_launches={e['creator_past_launches']}"
                               if e.get('creator_past_launches') is not None
                               else "creator_past_launches=unknown")
                            + f" creator_known={int(bool(e.get('creator_known')))}",
                        ]
                        parts[ins:ins] = block
                        content = '\n'.join(parts)
                        injected += 1
                lines.append({'role': msg.get('role'), 'content': content})
            r['messages'] = lines
            m['c9_enrichment'] = {k: e[k] for k in (
                'mcap_sol_at_t', 'mcap_source', 'holders_at_t', 'top1_float_share',
                'top5_float_share', 'holder_hhi', 'bundle_slots', 'bundle_wallets',
                'creator_past_launches', 'creator_known')}
            r['meta'] = m
            out.write(json.dumps(r, ensure_ascii=False) + '\n')
            kept += 1
    report[split] = {'kept': kept, 'injected': injected, 'dropped_management_like': dropped_mgmt,
                     'rows_without_enrichment': missing_enr, 'families': dict(fams)}
    print(f"{split}: {json.dumps(report[split])}")

json.dump(report, open('/training/v2/reports/C9_BUILD_REPORT.json', 'w', encoding='utf-8'), indent=1)
print("\nwrote", DST)
