#!/usr/bin/env python
"""Replace every retired cost figure in the entry (decision) family with the ONE
authority's number, computed from each row's own venue and pool depth.

WHY. The entry slice carried a hand-typed "210 bp round-trip cost" in its system prompt
and 255,366 occurrences of retired figures (210 / 280 / 180) across 85,086 rows, in a
corpus whose management family states a per-row, recomputable cost. Two families that
disagree about what a trade costs cannot train one brain.

WHAT IT DOES, per row, and nothing else:
  1. system prompt - the retired cost sentence is replaced by cost_authority's model
     statement (venue-aware, no hand-typed figure).
  2. user prompt - "Respect the 210 bp round-trip cost" -> "the stated round-trip cost",
     and the SIZE OPTIONS block is regenerated by cost_authority.size_options() from the
     row's own regime and the depth the block already reports.
  3. any surviving retired figure in user/assistant text is replaced by THAT row's
     FULL-clip round trip.
  4. meta gains a cost_authority block so the next auditor does not have to re-derive it.

Every other byte - the label, the barrier triplet, the enrichment block, the price units -
is passed through untouched. The label is NOT recomputed: this pass changes what the
prompt SAYS about cost, not what the row is labelled, so it must be provably unable to
move a label. `--verify-only` re-checks that.

Usage:
  python patch_entry_cost.py --splits train validation examination --dry-run
  python patch_entry_cost.py --splits train validation examination \
      --outdir /training/v2/candidate_sft_c10_entry
"""
import argparse
import collections
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cost_authority as CA  # noqa: E402

SRC = "/training/v2/candidate_sft_c9_r2"
# Retired CONTEXTS, never bare numbers: the authority legitimately computes a 210 bp or
# 280 bp round trip for a thin pool, and grepping for the digits flagged those as defects.
RETIRED = ("fees + slippage + priority + failure charge",
           "one-way execution cost",
           "Respect the 210 bp round-trip cost",
           "the 210 bp cost floor",
           "cost_model_bp",
           "round-trip cost measured at the decision clock",
           "not priceable at this book depth")

SYS_FROM = ("Round-trip cost (fees + slippage + priority + failure charge) is 210 bp. "
            "A BUY is only correct if the expected move can clear that cost.")
SYS_TO = CA.model_statement(uniform_venue_fee=False) + " A BUY is only correct if the expected move can clear that cost."
USER_FROM = "Respect the 210 bp round-trip cost."
USER_TO = "Respect the stated round-trip cost."

# Anchor on the header and consume the contiguous indented block. NOT on the block's
# closing sentence: the archived generator emitted at least two different closers
# ("...pays more impact in a thinner book." and a shorter one on unpriceable rows), and
# an exact-text match silently skipped those rows - they kept the retired figures AND the
# old "not priceable" claim, which is exactly the defect class this pass exists to remove.
RE_SIZE_BLOCK = re.compile(r"SIZE OPTIONS \(choose one on BUY;[^\n]*\):\n(?:  [^\n]*\n?)*")
RE_DEPTH = re.compile(r"pool depth ([0-9.]+) SOL")


def regime_of(meta):
    """The venue OUR next fill lands on. A graduated mint has a live PumpSwap pool; an
    un-graduated one does not. The curve object is retained after graduation with stale
    reserves (measured staleness in the archive: ~80 min), so 'curve.status == present'
    alone would mis-classify every graduated mint."""
    ms = meta.get("market_structure") or {}
    amm = (ms.get("amm") or {}).get("status")
    return "amm" if amm == "present" else "bonding_curve"


def depth_of(meta, regime, stats):
    """Pool depth in SOL, from the row's OWN reserves, not from the rendered text.

    The archived block refused to price 18% of rows ("not priceable at this book depth")
    while those same rows carry `pricing_eligible: true`, a live pool and 636 SOL of quote
    reserve in meta. The text was the unreliable source; meta is the authority."""
    ms = meta.get("market_structure") or {}
    if regime == "amm":
        src = (meta.get("amm_reserves") or {})
        lam = src.get("quote_reserve_lamports")
        if lam:
            stats["depth_from_amm_meta"] += 1
            return float(lam) / 1e9
        c = (ms.get("amm") or {}).get("quote_reserve_lamports") or (ms.get("amm") or {}).get("reserve_lamports")
        if c:
            stats["depth_from_amm_ms"] += 1
            return float(c) / 1e9
    src = (meta.get("curve_reserves") or {})
    lam = src.get("virtual_sol_reserves_lamports")
    if lam:
        stats["depth_from_curve_meta"] += 1
        return float(lam) / 1e9
    lam = (ms.get("curve") or {}).get("virtual_sol_reserves_lamports")
    if lam:
        stats["depth_from_curve_ms"] += 1
        return float(lam) / 1e9
    stats["no_depth_anywhere"] += 1
    return None


def patch_row(r, stats):
    meta = r["meta"]
    regime = regime_of(meta)
    u = r["messages"][1]["content"]
    if "not priceable at this book depth" in u:
        stats["was_unpriceable"] += 1
        if (meta.get("action") or "") == "BUY":
            stats["was_unpriceable_BUY"] += 1
    depth = depth_of(meta, regime, stats)
    m = RE_DEPTH.search(u)
    if depth is None:
        return None
    if m and abs(float(m.group(1)) - depth) > max(0.05, 0.01 * depth):
        stats["depth_text_vs_meta_mismatch"] += 1
    opts = CA.size_options(regime, depth, uniform_venue_fee=False)
    sizes = {k: v["round_trip_bp"] for k, v in opts["sizes"].items()}
    full_bp = sizes["FULL"]

    changed = 0
    # 1. system
    sysc = r["messages"][0]["content"]
    if SYS_FROM in sysc:
        r["messages"][0]["content"] = sysc.replace(SYS_FROM, SYS_TO)
        changed += 1
    elif "210 bp" in sysc:
        stats["system_sentence_unmatched"] += 1

    # 2. user: the respect sentence + the size block
    if USER_FROM in u:
        u = u.replace(USER_FROM, USER_TO)
        changed += 1
    if RE_SIZE_BLOCK.search(u):
        u = RE_SIZE_BLOCK.sub(opts["block"] + "\n", u)
        changed += 1
    else:
        stats["size_block_unmatched"] += 1

    # 2b. stale WORDING that asserts a fixed floor. The number may be right (a thin pool's
    # own round trip can compute to exactly 210 bp) but the phrase is indistinguishable
    # from the retired constant to any reader or gate, so it goes.
    for msg in r["messages"]:
        if "the 210 bp cost floor" in msg["content"]:
            msg["content"] = msg["content"].replace(
                "the 210 bp cost floor", f"the {full_bp} bp round-trip cost")
            changed += 1

    # 3. any surviving retired figure, in any message
    for msg in r["messages"]:
        for phrase in ("210 bp", "280 bp", "180 bp", "189 bp"):
            if phrase in msg["content"]:
                msg["content"] = msg["content"].replace(phrase, f"{full_bp} bp")
                stats[f"residual_{phrase.split()[0]}"] += 1
                changed += 1

    # WRITE THE USER MESSAGE BACK. Steps 2 and 3 rebind a local; without this the size
    # block substitution is computed and thrown away, and the row ships with the retired
    # figures it was supposed to lose.
    r["messages"][1]["content"] = u

    meta["cost_authority"] = {
        "regime": regime,
        "depth_sol": depth,
        "round_trip_bp": sizes,
        "authority": "cost_authority.size_options@uniform_venue_fee=False",
        "venue_bp_per_leg": opts["sizes"]["FULL"]["venue_bp_per_leg"],
    }
    stats["regime_" + regime] += 1
    stats["size_bp_full_" + str(full_bp)] += 0
    return changed


def verify(r):
    """Post-conditions. Cheap, and checked on every row, not sampled."""
    bad = []
    blob = "\n".join(m["content"] for m in r["messages"])
    for phrase in RETIRED:
        if phrase in blob:
            bad.append("retired:" + phrase)
    if "price_lamports_per_raw_token" not in blob:
        bad.append("units")
    ca = (r["meta"].get("cost_authority") or {})
    if not ca:
        bad.append("no_cost_authority_block")
    else:
        # RECOMPUTE from meta rather than grep for the string: a string match cannot tell
        # a correct number from a stale one that happens to survive.
        stats = collections.Counter()
        auth = CA.size_options(ca["regime"], ca["depth_sol"], uniform_venue_fee=False)
        for k, d in auth["sizes"].items():
            if d["round_trip_bp"] != ca["round_trip_bp"][k]:
                bad.append("size_bp_not_from_authority:" + k)
        if "not priceable at this book depth" in blob:
            bad.append("still_unpriceable")
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--splits", nargs="+", default=["train", "validation", "examination"])
    ap.add_argument("--outdir", default="/training/v2/candidate_sft_c10_entry")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--verify-only", action="store_true",
                    help="re-check an ALREADY patched directory, change nothing")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    src = args.outdir if args.verify_only else SRC
    if not args.dry_run and not args.verify_only:
        os.makedirs(args.outdir, exist_ok=True)

    report = {"suites": {}, "corpus_revision": "c10_entry_cost_pass"}
    for split in args.splits:
        stats = collections.Counter()
        rows_in = rows_out = 0
        bad_rows = collections.Counter()
        fout = None
        if not args.dry_run and not args.verify_only:
            fout = open(os.path.join(args.outdir, f"{split}.jsonl"), "w")
        with open(os.path.join(src, f"{split}.jsonl")) as fh:
            for line in fh:
                rows_in += 1
                if args.limit and rows_in > args.limit:
                    break
                r = json.loads(line)
                if not args.verify_only:
                    if patch_row(r, stats) is None:
                        continue
                bad = verify(r)
                if bad:
                    for b in bad:
                        bad_rows[b.split(":")[0]] += 1
                    stats["rows_with_defect"] += 1
                rows_out += 1
                if fout:
                    fout.write(json.dumps(r, separators=(",", ":")) + "\n")
        if fout:
            fout.close()
        report["suites"][split] = {"rows_in": rows_in, "rows_out": rows_out,
                                   "defects": dict(bad_rows), "stats": dict(stats)}
        print(split, rows_in, "->", rows_out, json.dumps(dict(bad_rows)), flush=True)
    out = "/training/v2/reports/ENTRY_COST_PASS.json"
    with open(out, "w") as fh:
        json.dump(report, fh, indent=1)
    tot = sum(v["defects"].get("retired", 0) + v["defects"].get("units", 0)
              + v["defects"].get("no_cost_authority_block", 0)
              + v["defects"].get("size_bp_not_in_text", 0)
              for v in report["suites"].values())
    print("TOTAL_DEFECT_ROWS", tot, "->", out)


if __name__ == "__main__":
    main()