//! §41 layout fixtures OBSERVED ON MAINNET. **GENERATED — do not hand-edit.**
//!
//! Generated by `tools/gen_layout_fixtures.py` from a live Helius RPC probe of
//! the pump.fun program `6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P`.
//!
//! Sample: **400 transactions**, 547 pump.fun instructions,
//! 259 identified. Every row below carries the **real** verifying
//! signature and slot of a transaction that exhibited that account count, so
//! `LayoutRegistry::record_verified` accepts it on its merits — no placeholder
//! passes the guard, and none is fabricated here.
//!
//! ## What the chain actually shows
//!
//! | instruction | accounts | notes |
//! |---|---|---|
//! | `buy` | **18** | both token programs; cashback does not change the count |
//! | `buy_exact_sol_in` | **18** | same layout as `buy` |
//! | `sell` | **16** | no cashback (+bonding_curve_v2 +BuybackVault) |
//! | `sell` | **17** | cashback (+user_volume_accumulator) |
//! | `buy_v2` | 27 | **not built by this engine** |
//! | `sell_v2` | 26 / 27 | **not built by this engine** |
//!
//! The old hand-rolled block registered **17** for a buy. No mainnet buy with 17
//! accounts exists in this sample: 17 is what `FeeTail::None` produces, and per
//! Rev-18 a 17-account buy fails on chain (`Custom(6062)`,
//! BuybackFeeRecipientMissing). Registering it was what let the gate accept a
//! layout the chain rejects. It is **not** registered here.
//!
//! `non_sol_quote` is false for every row: pump.fun bonding curves are
//! SOL-quoted, and the builder derives this dimension as
//! `quote_mint != WSOL_MINT`. (`docs/fixtures/layouts.json` records
//! `non_sol_quote: true` for pumpfun rows — that field does not agree with the
//! builder and is **not** trusted here; see the plan doc.)
//!
//! ## Coverage gaps (deliberate, fail-closed)
//!
//! `buy_v2`/`sell_v2` are **not** registered, because this engine never builds
//! them — registering a count the builder cannot emit would only widen the gate.
//! If pump.fun retires the legacy `buy` path, the builder must learn `buy_v2`
//! before those trades work; the gate will refuse rather than mis-build.

use pump_quant_protocol::layout::{
    is_plausible_signature, LayoutError, LayoutKey, LayoutRegistry, Side, Variant, Venue,
    VerifiedLayout,
};

/// (is_buy, cashback, token_2022, account_count, verifying_slot, verifying_signature)
const PUMPFUN_OBSERVED: &[(bool, bool, bool, usize, u64, [u8; 64])] = &[
    // buy, 18 accts — slot 448249388
    (
        true,
        false,
        true,
        18,
        448249388_u64,
        [
            0x10, 0xca, 0x49, 0x67, 0xef, 0x69, 0xf3, 0x52, 0xb5, 0x25, 0x6c, 0x4c, 0xbd, 0x9d,
            0x3e, 0xa5, 0x67, 0x83, 0xde, 0x7b, 0xc7, 0x1d, 0x52, 0xe7, 0x97, 0xd2, 0x67, 0x7c,
            0x68, 0x24, 0x37, 0xf3, 0xdd, 0xc8, 0x48, 0x85, 0x2a, 0xae, 0x0d, 0x23, 0x00, 0xe5,
            0xe9, 0xfb, 0xe7, 0x84, 0x3d, 0x8c, 0xd5, 0xe9, 0xd4, 0x62, 0xe7, 0xa8, 0xef, 0xb8,
            0x02, 0x9c, 0x0c, 0xe0, 0x4e, 0xed, 0x4e, 0x05,
        ],
    ),
    // buy, 18 accts (SPL token) — slot 448249373
    (
        true,
        false,
        false,
        18,
        448249373_u64,
        [
            0xc2, 0x74, 0xd3, 0xb2, 0x61, 0xec, 0x24, 0x86, 0x5e, 0x3f, 0xef, 0xbd, 0x1f, 0x0a,
            0xa3, 0xb5, 0xef, 0x32, 0x2c, 0xe6, 0x39, 0xe4, 0x53, 0xa1, 0x94, 0x00, 0x9e, 0xe6,
            0xc5, 0xd7, 0x50, 0xb0, 0x14, 0xc6, 0x47, 0x89, 0xb3, 0x54, 0xf2, 0x1a, 0x0b, 0x8d,
            0x0c, 0xdf, 0x47, 0xd2, 0xf0, 0x67, 0x55, 0x2a, 0xde, 0x82, 0x7f, 0x0d, 0x51, 0x8c,
            0x89, 0x78, 0x4f, 0xd1, 0xaa, 0xab, 0xdc, 0x01,
        ],
    ),
    // buy, 18 accts (cashback: the count does not change, only the ATA addrs) — slot 448249388
    (
        true,
        true,
        true,
        18,
        448249388_u64,
        [
            0x10, 0xca, 0x49, 0x67, 0xef, 0x69, 0xf3, 0x52, 0xb5, 0x25, 0x6c, 0x4c, 0xbd, 0x9d,
            0x3e, 0xa5, 0x67, 0x83, 0xde, 0x7b, 0xc7, 0x1d, 0x52, 0xe7, 0x97, 0xd2, 0x67, 0x7c,
            0x68, 0x24, 0x37, 0xf3, 0xdd, 0xc8, 0x48, 0x85, 0x2a, 0xae, 0x0d, 0x23, 0x00, 0xe5,
            0xe9, 0xfb, 0xe7, 0x84, 0x3d, 0x8c, 0xd5, 0xe9, 0xd4, 0x62, 0xe7, 0xa8, 0xef, 0xb8,
            0x02, 0x9c, 0x0c, 0xe0, 0x4e, 0xed, 0x4e, 0x05,
        ],
    ),
    // buy, 18 accts (cashback, SPL) — slot 448249373
    (
        true,
        true,
        false,
        18,
        448249373_u64,
        [
            0xc2, 0x74, 0xd3, 0xb2, 0x61, 0xec, 0x24, 0x86, 0x5e, 0x3f, 0xef, 0xbd, 0x1f, 0x0a,
            0xa3, 0xb5, 0xef, 0x32, 0x2c, 0xe6, 0x39, 0xe4, 0x53, 0xa1, 0x94, 0x00, 0x9e, 0xe6,
            0xc5, 0xd7, 0x50, 0xb0, 0x14, 0xc6, 0x47, 0x89, 0xb3, 0x54, 0xf2, 0x1a, 0x0b, 0x8d,
            0x0c, 0xdf, 0x47, 0xd2, 0xf0, 0x67, 0x55, 0x2a, 0xde, 0x82, 0x7f, 0x0d, 0x51, 0x8c,
            0x89, 0x78, 0x4f, 0xd1, 0xaa, 0xab, 0xdc, 0x01,
        ],
    ),
    // sell, 16 accts (no cashback) — slot 448249388
    (
        false,
        false,
        true,
        16,
        448249388_u64,
        [
            0x02, 0x4e, 0xcb, 0xc6, 0x5e, 0xb1, 0xbb, 0xf7, 0x3e, 0xb7, 0x6b, 0x0f, 0x81, 0x02,
            0xcb, 0x6d, 0x12, 0xec, 0xe8, 0x08, 0x9f, 0x9b, 0xab, 0xc1, 0x7d, 0x74, 0xd5, 0x3a,
            0xb4, 0x4b, 0x99, 0x90, 0xab, 0x28, 0xc7, 0xda, 0x1f, 0xac, 0x40, 0x60, 0xf8, 0x06,
            0x44, 0xbc, 0xa4, 0x0e, 0x22, 0x60, 0xac, 0x32, 0x72, 0x64, 0x32, 0x2d, 0xac, 0x17,
            0x23, 0xe9, 0x5f, 0x8d, 0x6c, 0x23, 0x64, 0x09,
        ],
    ),
    // sell, 16 accts (no cashback, SPL) — slot 448249374
    (
        false,
        false,
        false,
        16,
        448249374_u64,
        [
            0x2a, 0x6a, 0xfc, 0x1b, 0x07, 0x0c, 0xad, 0x6d, 0x67, 0x6e, 0xa7, 0x84, 0xba, 0x46,
            0xb3, 0xb2, 0xc4, 0xea, 0xa4, 0x61, 0x8a, 0x54, 0x4f, 0xcd, 0xfc, 0xe0, 0x8c, 0x72,
            0x48, 0x74, 0x5b, 0x56, 0x0f, 0xbd, 0x10, 0x60, 0x6a, 0x83, 0x5f, 0x75, 0xf6, 0x95,
            0xe7, 0x2c, 0x10, 0x02, 0x4f, 0xe8, 0x71, 0xcc, 0x9b, 0x76, 0x27, 0x0f, 0xf1, 0x1d,
            0xdc, 0x31, 0x3e, 0x6f, 0xb1, 0xb1, 0x76, 0x0f,
        ],
    ),
    // sell, 17 accts (cashback: +user_volume_accumulator) — slot 448249379
    (
        false,
        true,
        true,
        17,
        448249379_u64,
        [
            0xfb, 0x16, 0xf3, 0x45, 0x38, 0x7e, 0x4c, 0x02, 0xfc, 0xb7, 0x4f, 0xcf, 0x89, 0xf8,
            0x6a, 0x11, 0x20, 0x1a, 0xba, 0x6a, 0xad, 0x24, 0xf4, 0x01, 0xed, 0xe9, 0x16, 0x77,
            0xd7, 0xdf, 0xd0, 0x0e, 0xb8, 0x81, 0x21, 0x24, 0xdf, 0x5d, 0xbb, 0x09, 0xcf, 0x04,
            0xc1, 0xd1, 0x5f, 0xbc, 0x6e, 0x7b, 0xe8, 0x87, 0xc1, 0xe7, 0xaf, 0x95, 0x5b, 0x66,
            0xd7, 0x04, 0xb6, 0x0c, 0x00, 0x89, 0x74, 0x07,
        ],
    ),
    // sell, 17 accts (cashback); the count is token-program-independent, so the observed 17-account sell evidences both token programs — slot 448249379
    (
        false,
        true,
        false,
        17,
        448249379_u64,
        [
            0xfb, 0x16, 0xf3, 0x45, 0x38, 0x7e, 0x4c, 0x02, 0xfc, 0xb7, 0x4f, 0xcf, 0x89, 0xf8,
            0x6a, 0x11, 0x20, 0x1a, 0xba, 0x6a, 0xad, 0x24, 0xf4, 0x01, 0xed, 0xe9, 0x16, 0x77,
            0xd7, 0xdf, 0xd0, 0x0e, 0xb8, 0x81, 0x21, 0x24, 0xdf, 0x5d, 0xbb, 0x09, 0xcf, 0x04,
            0xc1, 0xd1, 0x5f, 0xbc, 0x6e, 0x7b, 0xe8, 0x87, 0xc1, 0xe7, 0xaf, 0x95, 0x5b, 0x66,
            0xd7, 0x04, 0xb6, 0x0c, 0x00, 0x89, 0x74, 0x07,
        ],
    ),
];

/// Register every pump.fun layout observed on mainnet.
///
/// Fails closed on the first row the registry refuses (a placeholder or a
/// duplicate key), so a corrupt table can never half-populate the gate.
pub fn register_observed_pumpfun_layouts(registry: &mut LayoutRegistry) -> Result<(), LayoutError> {
    for &(is_buy, cashback, token_2022, account_count, verifying_slot, verifying_signature) in
        PUMPFUN_OBSERVED
    {
        registry.record_verified(VerifiedLayout {
            key: LayoutKey {
                venue: Venue::PumpFun,
                side: if is_buy { Side::Buy } else { Side::Sell },
                variant: Variant {
                    cashback,
                    token_2022,
                    non_sol_quote: false,
                    reversed_pool: false,
                },
            },
            account_count,
            verifying_slot,
            verifying_signature,
        })?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generated table must be self-consistent AND acceptable to the gate.
    /// This is the guard for the generator: re-running it against a bad probe
    /// (or against a probe whose field names changed) fails HERE rather than
    /// silently widening or bricking the §41 gate.
    #[test]
    fn observed_table_registers_and_matches_the_chain() {
        let mut reg = LayoutRegistry::new();
        register_observed_pumpfun_layouts(&mut reg).expect("every observed row must register");
        assert_eq!(
            reg.verified().len(),
            PUMPFUN_OBSERVED.len(),
            "no row may silently replace another"
        );

        for &(is_buy, _cashback, _t22, count, slot, sig) in PUMPFUN_OBSERVED {
            assert!(
                is_plausible_signature(&sig),
                "observed rows must carry real signatures, not placeholders"
            );
            assert!(
                slot > 400_000_000,
                "verifying slot must look like a real mainnet slot"
            );
            if is_buy {
                assert_eq!(
                    count, 18,
                    "a mainnet pump.fun buy is 18 accounts — never 17"
                );
            } else {
                assert!(
                    count == 16 || count == 17,
                    "a mainnet pump.fun sell is 16 or 17"
                );
            }
        }

        // The gate must refuse the 17-account BUY that the daemon used to register
        // by hand: no mainnet transaction has ever shown that layout.
        let buy = LayoutKey {
            venue: Venue::PumpFun,
            side: Side::Buy,
            variant: Variant {
                cashback: false,
                token_2022: true,
                non_sol_quote: false,
                reversed_pool: false,
            },
        };
        assert!(
            matches!(
                reg.require(&buy, 17),
                Err(LayoutError::CountDisagrees { .. })
            ),
            "a 17-account buy must NOT clear the gate"
        );
        assert!(
            reg.require(&buy, 18).is_ok(),
            "the observed 18-account buy must clear the gate"
        );
    }
}
