//! **C3 annotation parity: the corpus's own curve/AMM producer vs `curve_annotation.rs`.**
//!
//! The fixture is generated by importing `build_sft_c6` (the authority that wrote the c12
//! rows) and running its `curve_state` / `amm_state` / `curve_line` / `amm_line` over a case
//! set. It carries the RAW INPUTS (reserves, timestamps, attribution facts) plus the
//! authority's rendered line, so this test can fail on a wrong renderer, a wrong unit, a
//! wrong rounding, or a wrong reason string - not merely on a self-inconsistency.
//!
//! # Two rules of comparison that have to be stated, not assumed
//!
//! 1. **The live clock is monotone.** The corpus reads a historical tape and picks the last
//!    row at or before `t_dec`; it can therefore answer `no_event_before_t_dec` for a tape
//!    whose only row is in the future. The live annotator never holds a future observation
//!    (time moves one way), so this test feeds exactly the observations with `ts <= t_dec` -
//!    the subset a live engine could have had. The case where the engine DOES somehow hold a
//!    future observation is covered by the annotator's own unit tests, which assert that a
//!    future snapshot is refused rather than used.
//! 2. **The corpus's AMM rows are pre-filtered to WSOL pools** (`load_amm_backfill` drops
//!    rows without decoded reserves and the attribution step only admits WSOL pools), so
//!    `quote_is_wsol` is set for every fixture row. The annotator's extra defence against a
//!    USDC-quoted pool is exercised by its unit tests instead, because the corpus's rows
//!    cannot express a USDC quote at all.

use pump_quant_app::curve_annotation::{
    AmmAttribution, AmmObservation, AnnotationState, CurveObservation, ANNOTATION_CAP_MS,
    LAMPORTS_PER_SOL, PRICING_BUDGET_MS, TOKEN_SCALE, V_GRAD_LAMPORTS,
};
use pump_quant_proposal::decision::{render_amm, render_curve};
use serde_json::Value;

fn fixture() -> Value {
    serde_json::from_str(include_str!("fixtures/c3_annotation_parity.json"))
        .expect("fixture parses")
}

/// The engine's mints are `[u8; 32]`; the fixture carries the corpus's base58-ish strings.
/// The key only has to be stable and unique per case, and every case uses one mint.
fn mint_key(s: &str) -> [u8; 32] {
    let mut m = [0u8; 32];
    for (i, b) in s.as_bytes().iter().take(32).enumerate() {
        m[i] = *b;
    }
    m
}

fn i64f(v: &Value, k: &str) -> i64 {
    v.get(k)
        .and_then(Value::as_i64)
        .unwrap_or_else(|| panic!("{k} present"))
}

#[test]
fn the_fixture_constants_are_the_rust_constants() {
    let f = fixture();
    let c = &f["constants"];
    assert_eq!(c["LAMPORTS_PER_SOL"].as_u64(), Some(LAMPORTS_PER_SOL));
    assert_eq!(c["TOKEN_SCALE"].as_u64(), Some(TOKEN_SCALE));
    assert_eq!(c["V_GRAD_LAMPORTS"].as_u64(), Some(V_GRAD_LAMPORTS));
    assert_eq!(
        c["ANNOTATION_CAP_MS"].as_i64(),
        Some(ANNOTATION_CAP_MS),
        "the annotation cap is a shared constant, not two numbers that happen to agree"
    );
    assert_eq!(c["PRICING_BUDGET_MS"].as_i64(), Some(PRICING_BUDGET_MS));
}

#[test]
fn c3_annotation_matches_the_corpus_producer_case_for_case() {
    let f = fixture();
    let cases = f["cases"].as_array().expect("cases");
    assert!(cases.len() >= 20, "the case set must cover both rule sets");

    let mut checked_present = 0usize;
    let mut checked_absent = 0usize;
    for (idx, case) in cases.iter().enumerate() {
        let kind = case["kind"].as_str().expect("kind");
        let mint = mint_key(case["mint"].as_str().expect("mint"));
        let t_dec = i64f(case, "t_dec_ms");
        let expected = case["expected_line_live"]
            .as_str()
            .expect("expected_line_live");
        let expected_present = case["expected_status_live"].as_str() == Some("present");

        let mut st = AnnotationState::new();
        let got = if kind == "curve" {
            for s in case["samples"].as_array().expect("samples") {
                let ts = i64f(s, "ts");
                if ts > t_dec {
                    continue; // rule 1: a live engine could not have held this yet
                }
                st.observe_curve(
                    mint,
                    CurveObservation {
                        v_sol_lamports: s["vsol"].as_u64().expect("vsol"),
                        v_tokens: s["vtok"].as_u64().expect("vtok"),
                        real_sol_lamports: s["rsol"].as_u64().expect("rsol"),
                        real_tokens: s["rtok"].as_u64().expect("rtok"),
                        ts_ms: ts,
                        slot: 0,
                    },
                );
            }
            render_curve(&st.curve_state(&mint, t_dec))
        } else {
            assert_eq!(kind, "amm", "unknown case kind");
            let wsol: Vec<String> = case["wsol_pools"]
                .as_array()
                .expect("wsol_pools")
                .iter()
                .map(|p| p.as_str().expect("pool").to_string())
                .collect();
            st.set_attribution(
                mint,
                AmmAttribution {
                    wsol_pools: wsol,
                    pools_total: case["pools_total"].as_u64().expect("pools_total") as usize,
                    graduated: case["graduated"].as_bool().expect("graduated"),
                },
            );
            if case["has_tape"].as_bool().unwrap_or(true) {
                for r in case["rows"].as_array().expect("rows") {
                    let ts = r[0].as_i64().expect("row ts");
                    if ts > t_dec {
                        continue;
                    }
                    st.observe_amm(
                        mint,
                        AmmObservation {
                            pool: r[1].as_str().expect("row pool").to_string(),
                            base_reserves_raw: r[2].as_u64().expect("row base"),
                            quote_reserves_lamports: r[3].as_u64().expect("row quote"),
                            quote_is_wsol: true, // rule 2
                            ts_ms: ts,
                            slot: r[4].as_u64().unwrap_or(0),
                        },
                    );
                }
            }
            render_amm(&st.amm_state(&mint, t_dec))
        };

        assert_eq!(
            got, expected,
            "case {idx} ({kind}) diverged from the corpus producer\n  rust: {got}\n  corpus: {expected}"
        );
        // The status must agree too: an annotator that hides a missing annotation behind a
        // zero-valued "present" line would otherwise pass a text comparison of the wrong kind.
        assert_eq!(
            got.contains("=present"),
            expected_present,
            "case {idx} ({kind}) present/absent disagrees with the corpus"
        );
        if expected_present {
            checked_present += 1;
        } else {
            checked_absent += 1;
        }
    }
    assert!(
        checked_present >= 8 && checked_absent >= 8,
        "the case set must exercise both outcomes (present {checked_present}, absent {checked_absent})"
    );
}

/// The tape-only expectations must stay distinguishable from the live ones, and the only
/// cases where they differ must be the ones a live engine could not have reached (a tape
/// whose observations are all in the future). If this ever starts failing, someone has
/// changed the comparison target without saying so.
#[test]
fn the_tape_and_live_expectations_differ_only_where_live_cannot_reach() {
    let f = fixture();
    let mut differing = 0usize;
    for case in f["cases"].as_array().expect("cases") {
        if case["live_differs"].as_bool() == Some(true) {
            differing += 1;
            assert_eq!(
                case["live_reachable"].as_bool(),
                Some(false),
                "a tape expectation that differs from the live one must be unreachable live"
            );
            assert!(
                case["expected_line"]
                    .as_str()
                    .unwrap()
                    .contains("no_event_before_t_dec"),
                "the unreachable cases are exactly the future-only tapes"
            );
        }
    }
    assert!(
        differing >= 2,
        "the fixture must record the unreachable cases ({differing} found)"
    );
}

/// A regression guard on the fixture itself: every absent case must carry a reason the two
/// producers share. If someone adds a case with a new reason string to one side only, this
/// fails before the comparison does.
#[test]
fn absent_reasons_are_the_shared_dialect() {
    let f = fixture();
    let known_curve = [
        "mint_absent",
        "no_event_before_t_dec",
        "older_than_annotation_cap",
        "nonpositive_reserve",
    ];
    let known_amm = [
        "never_graduated",
        "no_amm_event_in_backfill",
        "no_event_before_t_dec",
        "older_than_annotation_cap",
        "pool_not_authoritative_wsol",
        "nonpositive_reserve",
    ];
    let mut seen_curve = std::collections::BTreeSet::new();
    let mut seen_amm = std::collections::BTreeSet::new();
    for case in f["cases"].as_array().expect("cases") {
        let line = case["expected_line"].as_str().expect("line");
        let Some(rest) = line.split("reason=").nth(1) else {
            continue;
        };
        let reason = rest.trim();
        if case["kind"].as_str() == Some("curve") {
            assert!(
                known_curve.contains(&reason),
                "unknown curve reason {reason}"
            );
            seen_curve.insert(reason.to_string());
        } else {
            assert!(known_amm.contains(&reason), "unknown amm reason {reason}");
            seen_amm.insert(reason.to_string());
        }
    }
    assert!(
        seen_curve.len() >= 3,
        "curve reason coverage: {seen_curve:?}"
    );
    assert!(seen_amm.len() >= 4, "amm reason coverage: {seen_amm:?}");
}
