//! Parity harness: the live causal state ledger vs. the corpus authority.
//!
//! The fixture is generated by `gen_state_ledger_fixture.py`, which computes every expected
//! value with the corpus builder's OWN expressions (`build_states_v2._episode`, with `_ret_bp`
//! imported from that module), so a green test means the live ledger reproduces the corpus's
//! semantics — not that two hand-written expectations agree with each other.
//!
//! What this pins, in the order the corpus computes it: strictly-causal trade selection, the
//! last-finite-price rule, all-time counts/volumes/net flow minus the trades at or after the
//! clock, windowed trader concentration, the venue set over the last 200 trades, evidence
//! status from non-finite prices, momentum against the OLDEST finite price in each window, and
//! the population std of consecutive log returns inside 30 s.
//!
//! Float fields are compared twice: exactly-after-rounding (`rd(x, 5)`, which is what the
//! prompt actually renders) and to a relative 1e-9. The corpus's pipeline is numpy over small
//! arrays while this port sums serially, so a last-bit difference in the mean is possible in
//! principle; the *rendered* value is the contract, and that is asserted exactly.

use pump_quant_app::state_ledger::{StateLedger, StateTrade, VenueLabel};
use serde_json::Value;
use std::collections::BTreeMap;

fn fixture() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/state_ledger_parity.json"
    );
    let raw = std::fs::read_to_string(path).expect("fixture present");
    serde_json::from_str(&raw).expect("fixture is json")
}

fn venue_of(s: &str) -> VenueLabel {
    match s {
        "pumpfun" => VenueLabel::Pumpfun,
        "pumpswap" => VenueLabel::Pumpswap,
        _ => VenueLabel::Unknown,
    }
}

/// Python's `round(x, 5)` as the serializer applies it, reduced to the digits the prompt shows.
/// Ties are not exercised by this fixture (they are a separate, dedicated concern), so round
/// half away from zero is exact here.
fn rd5(x: f64) -> f64 {
    (x * 1e5).round() / 1e5
}

fn expect_close(field: &str, got: f64, want: f64) {
    let rel = if want == 0.0 {
        got.abs()
    } else {
        ((got - want) / want).abs()
    };
    assert!(
        rd5(got) == rd5(want) && rel <= 1e-9,
        "{field}: got {got:?} want {want:?} (rd5 {got_rd:?} vs {want_rd:?})",
        got_rd = rd5(got),
        want_rd = rd5(want)
    );
}

fn expect_opt_close(field: &str, got: Option<f64>, want: Option<f64>) {
    match (got, want) {
        (None, None) => {}
        (Some(g), Some(w)) => expect_close(field, g, w),
        _ => panic!("{field}: got {got:?} want {want:?}"),
    }
}

#[test]
fn the_live_ledger_reproduces_the_corpus_state_block() {
    let doc = fixture();
    let mut ledger = StateLedger::new();
    let mint = [7u8; 32];

    for t in doc["trades"].as_array().expect("trades") {
        let price = t["price_sol_per_raw"].as_f64();
        let trade = StateTrade {
            recv_unix_ms: t["recv_unix_ms"].as_i64().expect("t_ms"),
            price_sol_per_raw: price,
            sol_lamports_signed: t["sol_lamports_signed"].as_i64().expect("sol"),
            base_qty: Some(2_000_000),
            is_buy: t["is_buy"].as_bool().expect("side"),
            trader: t["trader"].as_u64().expect("trader"),
            venue: venue_of(t["venue"].as_str().expect("venue")),
        };
        assert!(ledger.on_trade(&mint, trade), "trade accepted");
    }

    let clocks = doc["clocks"].as_array().expect("clocks");
    assert!(clocks.len() >= 3, "the fixture must cover several clocks");
    for c in clocks {
        let t_dec = c["t_dec_ms"].as_i64().expect("t_dec");
        let want = &c["expected"];
        let got = ledger
            .serve(&mint, t_dec)
            .unwrap_or_else(|| panic!("snapshot served at {t_dec}"));

        assert_eq!(
            got.n_prior_trades,
            want["n_prior_trades"].as_u64().unwrap(),
            "n_prior_trades @{t_dec}"
        );
        assert_eq!(
            got.buy_count,
            want["buy_count"].as_u64().unwrap(),
            "@{t_dec}"
        );
        assert_eq!(
            got.sell_count,
            want["sell_count"].as_u64().unwrap(),
            "@{t_dec}"
        );
        assert_eq!(
            got.unique_traders,
            want["unique_traders"].as_u64().unwrap(),
            "unique_traders @{t_dec}"
        );
        assert_eq!(
            got.sol_volume_lamports,
            want["sol_volume_lamports"].as_i64().unwrap(),
            "sol_volume @{t_dec}"
        );
        assert_eq!(
            got.buy_volume_lamports,
            want["buy_volume_lamports"].as_i64().unwrap(),
            "buy_volume @{t_dec}"
        );
        assert_eq!(
            got.sell_volume_lamports,
            want["sell_volume_lamports"].as_i64().unwrap(),
            "sell_volume @{t_dec}"
        );
        assert_eq!(
            got.net_flow_lamports,
            want["net_flow_lamports"].as_i64().unwrap(),
            "net_flow @{t_dec}"
        );
        assert_eq!(
            got.price_sol_per_raw,
            want["price_sol_per_raw"].as_f64().unwrap(),
            "price @{t_dec}"
        );
        expect_close("age_s", got.age_s, want["age_s"].as_f64().unwrap());
        expect_close(
            "last_trade_age_s",
            got.last_trade_age_s,
            want["last_trade_age_s"].as_f64().unwrap(),
        );
        expect_opt_close(
            "top1_trader_share",
            got.top1_trader_share,
            want["top1_trader_share"].as_f64(),
        );
        expect_opt_close(
            "top5_trader_share",
            got.top5_trader_share,
            want["top5_trader_share"].as_f64(),
        );
        expect_opt_close(
            "buyer_seller_ratio",
            got.buyer_seller_ratio,
            want["buyer_seller_ratio"].as_f64(),
        );
        expect_opt_close(
            "price_volatility_30s_bp",
            got.price_volatility_30s_bp,
            want["price_volatility_30s_bp"].as_f64(),
        );
        expect_opt_close("ret_5s_bp", got.ret_5s_bp, want["ret_5s_bp"].as_f64());
        expect_opt_close("ret_30s_bp", got.ret_30s_bp, want["ret_30s_bp"].as_f64());
        expect_opt_close("ret_300s_bp", got.ret_300s_bp, want["ret_300s_bp"].as_f64());
        assert_eq!(got.venue, want["venue"].as_str().unwrap(), "venue @{t_dec}");
        assert_eq!(
            got.evidence_status,
            want["evidence_status"].as_str().unwrap(),
            "evidence_status @{t_dec}"
        );
        assert!(
            got.complete,
            "the fixture's tapes fit inside the ring @{t_dec}"
        );
    }
}

/// The guards the corpus relies on, stated as behaviour: a tail window with no trade is `n/a`
/// (not zero), the volatility floor is a *predecessor-trade* count, and dust never enters.
#[test]
fn the_corpus_guards_hold_at_their_boundaries() {
    let mut ledger = StateLedger::new();
    let mint = [3u8; 32];
    let t0 = 1_700_000_000_000i64;
    // 29 trades 1 s apart, so the 30-trade volatility floor is NOT yet met.
    for i in 0..29i64 {
        let ok = ledger.on_trade(
            &mint,
            StateTrade {
                recv_unix_ms: t0 + i * 1000,
                price_sol_per_raw: Some(2.0e-8 + i as f64 * 1e-10),
                sol_lamports_signed: -20_000_000,
                base_qty: Some(2_000_000),
                is_buy: true,
                trader: 1,
                venue: VenueLabel::Pumpfun,
            },
        );
        assert!(ok);
    }
    let s = ledger.serve(&mint, t0 + 29_000).expect("snapshot");
    assert_eq!(s.n_prior_trades, 29);
    assert_eq!(s.price_volatility_30s_bp, None, "29 priors < the 30 floor");
    // 5 s window at t0+29_000 holds trades 24..28; the oldest of them is the reference price.
    let p24 = 2.0e-8 + 24.0 * 1e-10;
    let p28 = 2.0e-8 + 28.0 * 1e-10;
    expect_close(
        "ret_5s_bp",
        s.ret_5s_bp.unwrap(),
        (p28 - p24) / p24 * 10_000.0,
    );
    // The 300 s window is wider than the whole tape, so it measures against the first print.
    expect_close(
        "ret_300s_bp",
        s.ret_300s_bp.expect("the 300 s window covers the tape"),
        (p28 - 2.0e-8) / 2.0e-8 * 10_000.0,
    );

    // The thirtieth predecessor unlocks volatility.
    assert!(ledger.on_trade(
        &mint,
        StateTrade {
            recv_unix_ms: t0 + 29_000,
            price_sol_per_raw: Some(2.0e-8 + 30.0 * 1e-10),
            sol_lamports_signed: -20_000_000,
            base_qty: Some(2_000_000),
            is_buy: true,
            trader: 1,
            venue: VenueLabel::Pumpfun,
        }
    ));
    let s = ledger.serve(&mint, t0 + 31_000).expect("snapshot");
    assert_eq!(s.n_prior_trades, 30);
    assert!(
        s.price_volatility_30s_bp.is_some(),
        "30 priors meet the floor, and 30 s of prices are retained"
    );
    assert_eq!(s.evidence_status, "complete");

    // Dust is refused at ingest and cannot move a count.
    assert!(!ledger.on_trade(
        &mint,
        StateTrade {
            recv_unix_ms: t0 + 32_000,
            price_sol_per_raw: Some(2.0e-8),
            sol_lamports_signed: -99_999,
            base_qty: Some(2_000_000),
            is_buy: true,
            trader: 1,
            venue: VenueLabel::Pumpfun,
        }
    ));
    let s2 = ledger.serve(&mint, t0 + 33_000).expect("snapshot");
    assert_eq!(s2.n_prior_trades, 30);

    // A non-finite price flips evidence to partial without breaking the price field.
    assert!(ledger.on_trade(
        &mint,
        StateTrade {
            recv_unix_ms: t0 + 33_000,
            price_sol_per_raw: None,
            sol_lamports_signed: -20_000_000,
            base_qty: Some(2_000_000),
            is_buy: true,
            trader: 1,
            venue: VenueLabel::Pumpfun,
        }
    ));
    let s3 = ledger.serve(&mint, t0 + 34_000).expect("snapshot");
    assert_eq!(s3.evidence_status, "partial");
    assert_eq!(
        s3.price_sol_per_raw,
        2.0e-8 + 30.0 * 1e-10,
        "the last FINITE price is the reference, not the missing one"
    );
}

/// Out-of-order arrivals are refused rather than sorted: the corpus's tape is time-sorted, and
/// a live ledger that reordered would invent an ordering it never observed.
#[test]
fn out_of_order_trades_are_refused() {
    let mut ledger = StateLedger::new();
    let mint = [9u8; 32];
    let mk = |t: i64, p: f64| StateTrade {
        recv_unix_ms: t,
        price_sol_per_raw: Some(p),
        sol_lamports_signed: -20_000_000,
        base_qty: Some(2_000_000),
        is_buy: true,
        trader: 1,
        venue: VenueLabel::Pumpswap,
    };
    assert!(ledger.on_trade(&mint, mk(1000, 1.0e-8)));
    assert!(ledger.on_trade(&mint, mk(2000, 1.1e-8)));
    assert!(
        !ledger.on_trade(&mint, mk(1500, 1.05e-8)),
        "late arrival refused"
    );
    assert_eq!(
        ledger.serve(&mint, 3000).expect("snapshot").n_prior_trades,
        2
    );
    // Equal timestamps ARE allowed (the tape can carry several prints per millisecond); the
    // clock's strict-prior rule is what excludes the tie, not the ingest.
    assert!(ledger.on_trade(&mint, mk(2000, 1.2e-8)));
    assert_eq!(
        ledger.serve(&mint, 2000).expect("snapshot").n_prior_trades,
        1,
        "recv_unix_ms == t_dec is EXCLUDED (searchsorted side=left)"
    );
    assert_eq!(
        ledger.serve(&mint, 2001).expect("snapshot").n_prior_trades,
        3
    );
}

/// A clock older than the retained window must be served `complete = false`, never silently
/// recomputed over a truncated tape.
#[test]
fn an_evicted_clock_is_flagged_incomplete() {
    let mut ledger = StateLedger::new();
    let mint = [11u8; 32];
    let ring = pump_quant_app::state_ledger::RING_CAP;
    for i in 0..(ring + 10) {
        let ok = ledger.on_trade(
            &mint,
            StateTrade {
                recv_unix_ms: 1_000_000 + i as i64 * 1000,
                price_sol_per_raw: Some(2.0e-8),
                sol_lamports_signed: -20_000_000,
                base_qty: Some(2_000_000),
                is_buy: true,
                trader: 1,
                venue: VenueLabel::Pumpfun,
            },
        );
        assert!(ok);
    }
    // At the newest trade, everything evicted is more than 300 s old and the ring still
    // holds more than the concentration window: the snapshot is exact.
    let newest = 1_000_000 + (ring as i64 + 9) * 1000;
    let now = ledger.serve(&mint, newest + 1).expect("snapshot");
    assert!(
        now.complete,
        "evictions older than every window leave the snapshot exact"
    );
    // A clock close to the oldest retained trade cannot be proven exact: evicted trades could
    // fall inside its 300 s window, so it must be flagged rather than guessed.
    let flagged = ledger.serve(&mint, 1_000_000 + 11_000).expect("snapshot");
    assert!(
        !flagged.complete,
        "a clock whose windows may have been evicted must be flagged"
    );
}

/// The per-trade bookkeeping the prompt leans on: counts, volumes and net flow are all-time
/// (minus the trades at or after the clock), while traders are windowed.
#[test]
fn counts_are_all_time_and_traders_are_windowed() {
    let mut ledger = StateLedger::new();
    let mint = [13u8; 32];
    let mut venues: BTreeMap<VenueLabel, usize> = BTreeMap::new();
    for i in 0..(pump_quant_app::state_ledger::CONC_WINDOW + 50) {
        let trader = (i % 3) as u64;
        *venues.entry(VenueLabel::Pumpfun).or_default() += 1;
        let ok = ledger.on_trade(
            &mint,
            StateTrade {
                recv_unix_ms: 5_000_000 + i as i64 * 100,
                price_sol_per_raw: Some(2.0e-8),
                sol_lamports_signed: if i % 2 == 0 { -30_000_000 } else { 10_000_000 },
                base_qty: Some(2_000_000),
                is_buy: i % 2 == 0,
                trader,
                venue: VenueLabel::Pumpfun,
            },
        );
        assert!(ok);
    }
    let s = ledger
        .serve(&mint, 5_000_000 + 1_000_000)
        .expect("snapshot");
    assert_eq!(
        s.n_prior_trades,
        (pump_quant_app::state_ledger::CONC_WINDOW + 50) as u64
    );
    assert_eq!(s.unique_traders, 3, "windowed, and three traders rotate");
    assert_eq!(s.buy_count + s.sell_count, s.n_prior_trades);
    assert_eq!(
        s.net_flow_lamports,
        s.buy_volume_lamports - s.sell_volume_lamports
    );
    assert_eq!(s.venue, "pumpfun");
    assert_eq!(s.buyer_seller_ratio, Some(1.0));
}
