import pandas as pd
l1 = pd.read_parquet('output/laserstream_gold_v3/l1_pump_state_v3.parquet')
print('L1 columns:', list(l1.columns))
print('L1 dtypes:')
for c in l1.columns:
    print(f'  {c}: {l1[c].dtype}')
print('L1 shape:', l1.shape)
print()
l2 = pd.read_parquet('output/laserstream_gold_v3/l2_pump_outcome_v3.parquet')
print('L2 columns:', list(l2.columns))
print('L2 shape:', l2.shape)
print()
l3 = pd.read_parquet('output/laserstream_gold_v3/l3_counterfactual_v3.parquet')
print('L3 columns:', list(l3.columns))
print('L3 shape:', l3.shape)
print()
l4 = pd.read_parquet('output/laserstream_gold_v3/l4_policy_eval_v3.parquet')
print('L4 columns:', list(l4.columns))
print('L4 shape:', l4.shape)
