//! Integration tests: `--replay` over each platform's saved raw-API-response
//! fixture must produce EXACTLY the NDJSON the Python twin's `normalize.py`
//! emits for the same objects — byte-for-byte (the expected strings below were
//! generated by running the actual Python normalizers over the fixtures) —
//! plus the deterministic synthetic `observed_at_ns` stamp (§22: replay is a
//! pure function of the fixture file; NO test touches the network). Missing
//! credentials must refuse to start with the Python twins' exact stderr
//! messages, before any socket could be opened.

use std::process::{Command, Output};

use pq_social_capture::json;

/// Fixed replay clock (must mirror `REPLAY_BASE_NS`/`REPLAY_STEP_NS`).
const BASE: u64 = 1_000_000_000;
const STEP: u64 = 1_000_000;

fn fixture(name: &str) -> String {
    format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"))
}

/// Run the binary with the given args and ALL adapter credentials scrubbed
/// from the environment — proof that replay (and refusal) is keyless.
fn run(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_pq-social-capture"))
        .args(args)
        .env_remove("TWITTERAPI_IO_KEY")
        .env_remove("TIKTOK_API_KEY")
        .env_remove("TIKTOK_API_BASE")
        .env_remove("FIRECRAWL_API_KEY")
        .output()
        .expect("binary runs")
}

fn stdout_lines(out: &Output) -> Vec<String> {
    String::from_utf8(out.stdout.clone())
        .expect("stdout is UTF-8")
        .lines()
        .map(String::from)
        .collect()
}

/// Splice the synthetic capture stamp into a `normalize.py`-shaped line —
/// the expected strings stay verbatim Python output.
fn with_stamp(python_line: &str, i: u64) -> String {
    let ts = BASE + i * STEP;
    format!(
        "{},\"observed_at_ns\":{ts}}}",
        python_line.strip_suffix('}').expect("object line")
    )
}

// ---------------------------------------------------------------- twitterapi

/// Verbatim `normalize.py` output for twitterapi_pages.json (dedupe applied),
/// generated by the Python twin's own `normalize_tweet`.
const TWITTER_EXPECTED: [&str; 4] = [
    "{\"platform\":\"x\",\"author\":\"cryptoKOL\",\"community\":\"\",\"text\":\"send it $WIF EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v\",\"likes\":420,\"reposts\":69,\"replies\":12,\"echo\":false}",
    "{\"platform\":\"x\",\"author\":\"echoAcct\",\"community\":\"\",\"text\":\"RT $WIF to the moon \u{1F680}\",\"likes\":2,\"reposts\":0,\"replies\":0,\"echo\":true}",
    "{\"platform\":\"x\",\"author\":\"unknown\",\"community\":\"\",\"text\":\"quote pumping \\\"hard\\\"\",\"likes\":7,\"reposts\":0,\"replies\":1,\"echo\":true}",
    "{\"platform\":\"x\",\"author\":\"replyGuy\",\"community\":\"\",\"text\":\"replying about $BONK\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":true}",
];

#[test]
fn twitterapi_replay_is_byte_exact_python_output() {
    let out = run(&["twitterapi", "--replay", &fixture("twitterapi_pages.json")]);
    assert!(out.status.success(), "{out:?}");
    let lines = stdout_lines(&out);
    let expected: Vec<String> = TWITTER_EXPECTED
        .iter()
        .enumerate()
        .map(|(i, l)| with_stamp(l, i as u64))
        .collect();
    assert_eq!(
        lines,
        expected,
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    // The duplicate id on page 2 was deduplicated across polls: 5 raw tweets
    // in the fixture, 4 emitted.
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 4 events"));
}

#[test]
fn twitterapi_replay_is_deterministic_across_runs() {
    let a = run(&["twitterapi", "--replay", &fixture("twitterapi_pages.json")]);
    let b = run(&["twitterapi", "--replay", &fixture("twitterapi_pages.json")]);
    assert_eq!(a.stdout, b.stdout, "byte-identical replays (§22)");
}

// -------------------------------------------------------------------- tiktok

/// Verbatim `normalize.py` output for tiktok_feed.json (dedupe applied).
const TIKTOK_EXPECTED: [&str; 3] = [
    "{\"platform\":\"tiktok\",\"author\":\"memelord\",\"community\":\"\",\"text\":\"this $WIF coin is insane EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v #solana #memecoin\",\"likes\":12000,\"reposts\":800,\"replies\":300,\"echo\":false}",
    "{\"platform\":\"tiktok\",\"author\":\"nickfallback\",\"community\":\"\",\"text\":\"provider B shape $BONK #pumpfun #crypto\",\"likes\":5,\"reposts\":1,\"replies\":2,\"echo\":false}",
    "{\"platform\":\"tiktok\",\"author\":\"duetguy\",\"community\":\"\",\"text\":\"duet reacting to $WIF\",\"likes\":50,\"reposts\":1,\"replies\":2,\"echo\":true}",
];

#[test]
fn tiktok_replay_is_byte_exact_python_output() {
    let out = run(&["tiktok", "--replay", &fixture("tiktok_feed.json")]);
    assert!(out.status.success(), "{out:?}");
    let lines = stdout_lines(&out);
    let expected: Vec<String> = TIKTOK_EXPECTED
        .iter()
        .enumerate()
        .map(|(i, l)| with_stamp(l, i as u64))
        .collect();
    assert_eq!(
        lines,
        expected,
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 3 events"));
}

// ----------------------------------------------------------------- firecrawl

/// Verbatim `normalize.py` output for firecrawl_scrape.json (the third saved
/// response has an empty markdown and emits nothing, like the Python `if md:`).
const FIRECRAWL_EXPECTED: [&str; 2] = [
    "{\"platform\":\"web\",\"author\":\"www.dexscreener.com\",\"community\":\"www.dexscreener.com\",\"text\":\"# Trending on Solana\\n\\n$WIF EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v and $BONK\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false}",
    "{\"platform\":\"web\",\"author\":\"www.dexscreener.com\",\"community\":\"www.dexscreener.com\",\"text\":\"top-level content fallback $PONKE\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false}",
];

#[test]
fn firecrawl_replay_is_byte_exact_python_output() {
    let out = run(&[
        "firecrawl",
        "--url",
        "https://www.dexscreener.com/solana",
        "--replay",
        &fixture("firecrawl_scrape.json"),
    ]);
    assert!(out.status.success(), "{out:?}");
    let lines = stdout_lines(&out);
    let expected: Vec<String> = FIRECRAWL_EXPECTED
        .iter()
        .enumerate()
        .map(|(i, l)| with_stamp(l, i as u64))
        .collect();
    assert_eq!(
        lines,
        expected,
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 2 events"));
}

#[test]
fn firecrawl_replay_without_urls_refuses_like_python() {
    // No --url and no sources.yaml in the test cwd: the Python twin's exact
    // message and exit code.
    let out = run(&["firecrawl", "--replay", &fixture("firecrawl_scrape.json")]);
    assert_eq!(out.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&out.stderr)
        .contains("no pages configured (sources.yaml web.pages) and no --url"));
    assert!(
        out.stdout.is_empty(),
        "stdout stays NDJSON-only (nothing here)"
    );
}

// ----------------------------------------------------- credentials + hygiene

#[test]
fn missing_credentials_refuse_with_python_twin_messages() {
    let cases: [(&[&str], &str); 3] = [
        (
            &["twitterapi"],
            "error: set TWITTERAPI_IO_KEY (https://twitterapi.io, pay-as-you-go)",
        ),
        (
            &["tiktok"],
            "error: set TIKTOK_API_KEY and TIKTOK_API_BASE (your provider endpoint)",
        ),
        (
            &["firecrawl", "--url", "https://pump.fun/board"],
            "error: set FIRECRAWL_API_KEY (https://firecrawl.dev)",
        ),
    ];
    for (args, msg) in cases {
        let out = run(args);
        assert_eq!(out.status.code(), Some(2), "{args:?}");
        let stderr = String::from_utf8_lossy(&out.stderr);
        assert!(stderr.contains(msg), "{args:?} stderr: {stderr}");
        assert!(out.stdout.is_empty(), "{args:?} must not write stdout");
    }
}

#[test]
fn unknown_subcommand_exits_2_with_usage() {
    let out = run(&["telegram"]);
    assert_eq!(out.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&out.stderr).contains("unknown subcommand"));
}

#[test]
fn every_replay_line_round_trips_as_valid_json_with_schema_order() {
    for (args, platform) in [
        (
            vec!["twitterapi", "--replay", &*fixture("twitterapi_pages.json")],
            "x",
        ),
        (
            vec!["tiktok", "--replay", &*fixture("tiktok_feed.json")],
            "tiktok",
        ),
        (
            vec![
                "firecrawl",
                "--url",
                "https://pump.fun/board",
                "--replay",
                &*fixture("firecrawl_scrape.json"),
            ],
            "web",
        ),
    ] {
        let out = run(&args);
        assert!(out.status.success(), "{args:?}");
        for line in stdout_lines(&out) {
            let v = json::parse(&line).unwrap_or_else(|e| panic!("invalid JSON {line:?}: {e}"));
            // Round-trip: re-serializing must reproduce the emitted bytes
            // exactly (proves the hand-rolled escape fn is canonical).
            assert_eq!(json::serialize(&v), line, "round-trip drift");
            let json::Value::Object(pairs) = &v else {
                panic!("top level must be an object");
            };
            let keys: Vec<&str> = pairs.iter().map(|(k, _)| k.as_str()).collect();
            // Exactly the normalize.py fields, in normalize.py order, plus the
            // capture stamp — the contract the deterministic core consumes.
            assert_eq!(
                keys,
                [
                    "platform",
                    "author",
                    "community",
                    "text",
                    "likes",
                    "reposts",
                    "replies",
                    "echo",
                    "observed_at_ns"
                ]
            );
            assert_eq!(
                pairs[0].1,
                json::Value::String(platform.to_string()),
                "platform tag"
            );
        }
    }
}
