//! Integration tests: `--replay` over each platform's saved raw-API-response
//! fixture must produce EXACTLY the NDJSON the Python twin's `normalize.py`
//! emits for the same objects — byte-for-byte (the expected strings below were
//! generated by running the actual Python normalizers over the fixtures) —
//! plus the deterministic synthetic `observed_at_ns` stamp (§22: replay is a
//! pure function of the fixture file; NO test touches the network). Missing
//! credentials must refuse to start with the Python twins' exact stderr
//! messages, before any socket could be opened.

use std::process::{Command, Output};

use pq_social_capture::json;

/// Fixed replay clock (must mirror `REPLAY_BASE_NS`/`REPLAY_STEP_NS`).
const BASE: u64 = 1_000_000_000;
const STEP: u64 = 1_000_000;

fn fixture(name: &str) -> String {
    format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"))
}

/// Run the binary with the given args and ALL adapter credentials scrubbed
/// from the environment — proof that replay (and refusal) is keyless.
fn run(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_pq-social-capture"))
        .args(args)
        .env_remove("TWITTERAPI_IO_KEY")
        .env_remove("TIKTOK_API_KEY")
        .env_remove("TIKTOK_API_BASE")
        .env_remove("FIRECRAWL_API_KEY")
        .env_remove("CG_API_KEY")
        .output()
        .expect("binary runs")
}

fn stdout_lines(out: &Output) -> Vec<String> {
    String::from_utf8(out.stdout.clone())
        .expect("stdout is UTF-8")
        .lines()
        .map(String::from)
        .collect()
}

/// Splice the synthetic capture stamp into a `normalize.py`-shaped line —
/// the expected strings stay verbatim Python output.
fn with_stamp(python_line: &str, i: u64) -> String {
    let ts = BASE + i * STEP;
    format!(
        "{},\"observed_at_ns\":{ts}}}",
        python_line.strip_suffix('}').expect("object line")
    )
}

// ---------------------------------------------------------------- twitterapi

/// Verbatim `normalize.py` output for twitterapi_pages.json (dedupe applied),
/// generated by the Python twin's own `normalize_tweet`.
const TWITTER_EXPECTED: [&str; 4] = [
    "{\"platform\":\"x\",\"author\":\"cryptoKOL\",\"community\":\"\",\"text\":\"send it $WIF EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v\",\"likes\":420,\"reposts\":69,\"replies\":12,\"echo\":false}",
    "{\"platform\":\"x\",\"author\":\"echoAcct\",\"community\":\"\",\"text\":\"RT $WIF to the moon \u{1F680}\",\"likes\":2,\"reposts\":0,\"replies\":0,\"echo\":true}",
    "{\"platform\":\"x\",\"author\":\"unknown\",\"community\":\"\",\"text\":\"quote pumping \\\"hard\\\"\",\"likes\":7,\"reposts\":0,\"replies\":1,\"echo\":true}",
    "{\"platform\":\"x\",\"author\":\"replyGuy\",\"community\":\"\",\"text\":\"replying about $BONK\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":true}",
];

#[test]
fn twitterapi_replay_is_byte_exact_python_output() {
    let out = run(&["twitterapi", "--replay", &fixture("twitterapi_pages.json")]);
    assert!(out.status.success(), "{out:?}");
    let lines = stdout_lines(&out);
    let expected: Vec<String> = TWITTER_EXPECTED
        .iter()
        .enumerate()
        .map(|(i, l)| with_stamp(l, i as u64))
        .collect();
    assert_eq!(
        lines,
        expected,
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    // The duplicate id on page 2 was deduplicated across polls: 5 raw tweets
    // in the fixture, 4 emitted.
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 4 events"));
}

#[test]
fn twitterapi_replay_is_deterministic_across_runs() {
    let a = run(&["twitterapi", "--replay", &fixture("twitterapi_pages.json")]);
    let b = run(&["twitterapi", "--replay", &fixture("twitterapi_pages.json")]);
    assert_eq!(a.stdout, b.stdout, "byte-identical replays (§22)");
}

// -------------------------------------------------------------------- tiktok

/// Verbatim `normalize.py` output for tiktok_feed.json (dedupe applied).
const TIKTOK_EXPECTED: [&str; 3] = [
    "{\"platform\":\"tiktok\",\"author\":\"memelord\",\"community\":\"\",\"text\":\"this $WIF coin is insane EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v #solana #memecoin\",\"likes\":12000,\"reposts\":800,\"replies\":300,\"echo\":false}",
    "{\"platform\":\"tiktok\",\"author\":\"nickfallback\",\"community\":\"\",\"text\":\"provider B shape $BONK #pumpfun #crypto\",\"likes\":5,\"reposts\":1,\"replies\":2,\"echo\":false}",
    "{\"platform\":\"tiktok\",\"author\":\"duetguy\",\"community\":\"\",\"text\":\"duet reacting to $WIF\",\"likes\":50,\"reposts\":1,\"replies\":2,\"echo\":true}",
];

#[test]
fn tiktok_replay_is_byte_exact_python_output() {
    let out = run(&["tiktok", "--replay", &fixture("tiktok_feed.json")]);
    assert!(out.status.success(), "{out:?}");
    let lines = stdout_lines(&out);
    let expected: Vec<String> = TIKTOK_EXPECTED
        .iter()
        .enumerate()
        .map(|(i, l)| with_stamp(l, i as u64))
        .collect();
    assert_eq!(
        lines,
        expected,
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 3 events"));
}

// ----------------------------------------------------------------- firecrawl

/// Verbatim `normalize.py` output for firecrawl_scrape.json (the third saved
/// response has an empty markdown and emits nothing, like the Python `if md:`).
const FIRECRAWL_EXPECTED: [&str; 2] = [
    "{\"platform\":\"web\",\"author\":\"www.dexscreener.com\",\"community\":\"www.dexscreener.com\",\"text\":\"# Trending on Solana\\n\\n$WIF EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v and $BONK\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false}",
    "{\"platform\":\"web\",\"author\":\"www.dexscreener.com\",\"community\":\"www.dexscreener.com\",\"text\":\"top-level content fallback $PONKE\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false}",
];

#[test]
fn firecrawl_replay_is_byte_exact_python_output() {
    let out = run(&[
        "firecrawl",
        "--url",
        "https://www.dexscreener.com/solana",
        "--replay",
        &fixture("firecrawl_scrape.json"),
    ]);
    assert!(out.status.success(), "{out:?}");
    let lines = stdout_lines(&out);
    let expected: Vec<String> = FIRECRAWL_EXPECTED
        .iter()
        .enumerate()
        .map(|(i, l)| with_stamp(l, i as u64))
        .collect();
    assert_eq!(
        lines,
        expected,
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 2 events"));
}

#[test]
fn firecrawl_replay_without_urls_refuses_like_python() {
    // No --url and no sources.yaml in the test cwd: the Python twin's exact
    // message and exit code.
    let out = run(&["firecrawl", "--replay", &fixture("firecrawl_scrape.json")]);
    assert_eq!(out.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&out.stderr)
        .contains("no pages configured (sources.yaml web.pages) and no --url"));
    assert!(
        out.stdout.is_empty(),
        "stdout stays NDJSON-only (nothing here)"
    );
}

// ---------------------------------------------------------------------- pump

/// Expected pump-lane output for pump_replies.json: 10 fixture entries →
/// 8 lines (one malformed entry skipped, one duplicate id deduped). The pump
/// lane has no Python twin — this tier-3 lane is Rust-first — so the expected
/// strings are the hand-audited normalization contract itself: author = reply
/// wallet LOWERCASED, community = thread mint VERBATIM case, zero engagement,
/// `echo:false`, and the one extra trailing field `"mint"` (thread context is
/// a mint-grade coin reference).
const PUMP_EXPECTED: [&str; 8] = [
    "{\"platform\":\"pump\",\"author\":\"7xkaccpqgmvz3fknojfwhdcprjiobgspqqhbg2g6oyqx\",\"community\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"text\":\"dev is based lfg\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1000000000,\"mint\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\"}",
    "{\"platform\":\"pump\",\"author\":\"fhkrtsnpmxaeqvjc8x1psvka4trqfjmshomshrvyu2b4\",\"community\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"text\":\"floor is in, adding here\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1001000000,\"mint\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\"}",
    "{\"platform\":\"pump\",\"author\":\"gkenvpnz5ymqlwuurrtbxcvdeeffgghhjjkkllmmnnpp\",\"community\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"text\":\"this is the next $WIF fr\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1002000000,\"mint\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\"}",
    "{\"platform\":\"pump\",\"author\":\"bqxwyvutsrqponmlkjihgfedcbaz1234567890abcdef\",\"community\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"text\":\"compare EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v flow before you ape\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1003000000,\"mint\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\"}",
    "{\"platform\":\"pump\",\"author\":\"so1anastreamerxxyyzz1122334455667788990011ab\",\"community\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"text\":\"send it \u{1F680}\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1004000000,\"mint\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\"}",
    "{\"platform\":\"pump\",\"author\":\"unknown\",\"community\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"text\":\"who is buying this\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1005000000,\"mint\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\"}",
    "{\"platform\":\"pump\",\"author\":\"degenwallet999888777666555444333222111aaabbb\",\"community\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"text\":\"\\\"rug\\\" fud is priced in\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1006000000,\"mint\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\"}",
    "{\"platform\":\"pump\",\"author\":\"kothhunteraaabbbcccdddeeefffggghhhiiijjjkkkl\",\"community\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"text\":\"koth soon\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1007000000,\"mint\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\"}",
];

#[test]
fn pump_replay_is_byte_exact() {
    let out = run(&["pump", "--replay", &fixture("pump_replies.json")]);
    assert!(out.status.success(), "{out:?}");
    assert_eq!(
        stdout_lines(&out),
        PUMP_EXPECTED,
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    // 10 raw entries: 1 malformed skipped + 1 duplicate id deduped = 8.
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 8 events"));
}

#[test]
fn pump_wrapped_object_variant_replays() {
    let out = run(&["pump", "--replay", &fixture("pump_replies_wrapped.json")]);
    assert!(out.status.success(), "{out:?}");
    let lines = stdout_lines(&out);
    assert_eq!(lines.len(), 2, "3 wrapped entries, 1 duplicate id deduped");
    assert!(lines[0].contains("\"community\":\"6tPg3KVqZBN8jVg2Fu3eYhTWKRXVxTDyyBs76cUCfpump\""));
    assert!(lines[0].contains("\"text\":\"wrapped-object response shape\""));
    assert!(lines[0].ends_with(",\"mint\":\"6tPg3KVqZBN8jVg2Fu3eYhTWKRXVxTDyyBs76cUCfpump\"}"));
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 2 events"));
}

#[test]
fn pump_replay_is_deterministic_across_runs() {
    let a = run(&["pump", "--replay", &fixture("pump_replies.json")]);
    let b = run(&["pump", "--replay", &fixture("pump_replies.json")]);
    assert_eq!(a.stdout, b.stdout, "byte-identical replays (§22)");
    assert_eq!(a.stderr, b.stderr, "diagnostics deterministic too");
}

#[test]
fn pump_schema_drift_is_logged_and_survived() {
    let out = run(&["pump", "--replay", &fixture("pump_drift.json")]);
    assert!(
        out.status.success(),
        "drift must NOT kill the lane: {out:?}"
    );
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("SCHEMA_DRIFT replies: shape "),
        "drift is loud on stderr: {stderr}"
    );
    assert!(stderr.contains(" -> "), "old AND new hash logged: {stderr}");
    assert_eq!(
        stdout_lines(&out).len(),
        2,
        "the tolerant parser keeps emitting through the drift"
    );
}

#[test]
fn pump_lines_carry_the_shared_schema_plus_trailing_mint() {
    let out = run(&["pump", "--replay", &fixture("pump_replies.json")]);
    assert!(out.status.success());
    for line in stdout_lines(&out) {
        let v = json::parse(&line).unwrap_or_else(|e| panic!("invalid JSON {line:?}: {e}"));
        assert_eq!(json::serialize(&v), line, "round-trip drift");
        let json::Value::Object(pairs) = &v else {
            panic!("top level must be an object");
        };
        let keys: Vec<&str> = pairs.iter().map(|(k, _)| k.as_str()).collect();
        // The normalize.py schema + capture stamp, then the ONE pump-specific
        // field LAST: the thread's mint (a mint-grade coin reference).
        assert_eq!(
            keys,
            [
                "platform",
                "author",
                "community",
                "text",
                "likes",
                "reposts",
                "replies",
                "echo",
                "observed_at_ns",
                "mint"
            ]
        );
        assert_eq!(pairs[0].1, json::Value::String("pump".to_string()));
        assert_eq!(pairs[2].1, pairs[9].1, "community and mint agree");
    }
}

#[test]
fn pump_without_mints_file_refuses_before_any_network() {
    let out = run(&["pump"]);
    assert_eq!(out.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&out.stderr)
        .contains("error: pump needs --mints-file (one base58 mint per line)"));
    assert!(out.stdout.is_empty(), "stdout stays NDJSON-only");
}

// ----------------------------------------------------- credentials + hygiene

#[test]
fn missing_credentials_refuse_with_python_twin_messages() {
    let cases: [(&[&str], &str); 3] = [
        (
            &["twitterapi"],
            "error: set TWITTERAPI_IO_KEY (https://twitterapi.io, pay-as-you-go)",
        ),
        (
            &["tiktok"],
            "error: set TIKTOK_API_KEY and TIKTOK_API_BASE (your provider endpoint)",
        ),
        (
            &["firecrawl", "--url", "https://pump.fun/board"],
            "error: set FIRECRAWL_API_KEY (https://firecrawl.dev)",
        ),
    ];
    for (args, msg) in cases {
        let out = run(args);
        assert_eq!(out.status.code(), Some(2), "{args:?}");
        let stderr = String::from_utf8_lossy(&out.stderr);
        assert!(stderr.contains(msg), "{args:?} stderr: {stderr}");
        assert!(out.stdout.is_empty(), "{args:?} must not write stdout");
    }
}

#[test]
fn unknown_subcommand_exits_2_with_usage() {
    let out = run(&["telegram"]);
    assert_eq!(out.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&out.stderr).contains("unknown subcommand"));
}

#[test]
fn every_replay_line_round_trips_as_valid_json_with_schema_order() {
    for (args, platform) in [
        (
            vec!["twitterapi", "--replay", &*fixture("twitterapi_pages.json")],
            "x",
        ),
        (
            vec!["tiktok", "--replay", &*fixture("tiktok_feed.json")],
            "tiktok",
        ),
        (
            vec![
                "firecrawl",
                "--url",
                "https://pump.fun/board",
                "--replay",
                &*fixture("firecrawl_scrape.json"),
            ],
            "web",
        ),
    ] {
        let out = run(&args);
        assert!(out.status.success(), "{args:?}");
        for line in stdout_lines(&out) {
            let v = json::parse(&line).unwrap_or_else(|e| panic!("invalid JSON {line:?}: {e}"));
            // Round-trip: re-serializing must reproduce the emitted bytes
            // exactly (proves the hand-rolled escape fn is canonical).
            assert_eq!(json::serialize(&v), line, "round-trip drift");
            let json::Value::Object(pairs) = &v else {
                panic!("top level must be an object");
            };
            let keys: Vec<&str> = pairs.iter().map(|(k, _)| k.as_str()).collect();
            // Exactly the normalize.py fields, in normalize.py order, plus the
            // capture stamp — the contract the deterministic core consumes.
            assert_eq!(
                keys,
                [
                    "platform",
                    "author",
                    "community",
                    "text",
                    "likes",
                    "reposts",
                    "replies",
                    "echo",
                    "observed_at_ns"
                ]
            );
            assert_eq!(
                pairs[0].1,
                json::Value::String(platform.to_string()),
                "platform tag"
            );
        }
    }
}

// ----------------------------------------------------------------- coingecko

/// Expected coingecko-lane output for coingecko_trending.json: 2 saved polls,
/// 5 raw observations → 4 lines (the re-trending coin and the repeated
/// category deduplicate; trending NFTs are ignored by design). No Python twin
/// — the expected strings are the hand-audited normalization contract:
/// author = "coingecko" (the aggregator is the actor), community =
/// "trending", zero engagement, `echo:false`, and optional trailing fields
/// ONLY when the vendor stated them (a null `market_cap_rank` drops the
/// `rank=` clause instead of faking a zero).
const COINGECKO_TRENDING_EXPECTED: [&str; 4] = [
    "{\"platform\":\"coingecko\",\"author\":\"coingecko\",\"community\":\"trending\",\"text\":\"TRENDING dogwifhat ($WIF) rank=98\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1000000000,\"aggregator_listed\":true}",
    "{\"platform\":\"coingecko\",\"author\":\"coingecko\",\"community\":\"trending\",\"text\":\"TRENDING Useless Coin ($USELESS)\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1001000000,\"aggregator_listed\":true}",
    "{\"platform\":\"coingecko\",\"author\":\"coingecko\",\"community\":\"trending\",\"text\":\"TRENDING CATEGORY Pump.fun Ecosystem\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1002000000}",
    "{\"platform\":\"coingecko\",\"author\":\"coingecko\",\"community\":\"trending\",\"text\":\"TRENDING Hosico Cat ($HOSICO) rank=601\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1003000000,\"aggregator_listed\":true}",
];

/// Expected output for coingecko_contract.json: 3 saved contract lookups of
/// one watched mint → 2 lines. Poll 1 is the AGGREGATOR-LISTED legibility
/// event (`LISTED …`, sentiment 87.5% → 8750 bp, 1234 watchlist users →
/// conf 1234 bp); poll 2's changed sentiment re-emits as `SENTIMENT …`
/// (91.25% → 9125 bp); poll 3 is identical to poll 2 and deduplicates (an
/// unchanged gauge is a quiet poll). community = the mint VERBATIM base58
/// case, exactly like the pump lane.
const COINGECKO_CONTRACT_EXPECTED: [&str; 2] = [
    "{\"platform\":\"coingecko\",\"author\":\"coingecko\",\"community\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"text\":\"LISTED Fartcoin ($FARTCOIN) 9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump rank=120\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1000000000,\"mint\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"aggregator_listed\":true,\"sentiment_bp\":8750,\"sentiment_conf_bp\":1234,\"sentiment_model\":\"coingecko-votes-v1\"}",
    "{\"platform\":\"coingecko\",\"author\":\"coingecko\",\"community\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"text\":\"SENTIMENT 9125bp Fartcoin ($FARTCOIN) 9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1001000000,\"mint\":\"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump\",\"aggregator_listed\":true,\"sentiment_bp\":9125,\"sentiment_conf_bp\":2500,\"sentiment_model\":\"coingecko-votes-v1\"}",
];

/// Expected output for coingecko_markets.json with `--category pump-fun`:
/// 2 saved roster polls, 4 raw entries → 3 lines (the repeated coin
/// deduplicates by roster identity even though its rank moved — a rank move
/// is not a NEW listing). community = the category id.
const COINGECKO_MARKETS_EXPECTED: [&str; 3] = [
    "{\"platform\":\"coingecko\",\"author\":\"coingecko\",\"community\":\"pump-fun\",\"text\":\"LISTED Fartcoin ($FARTCOIN) rank=120\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1000000000,\"aggregator_listed\":true}",
    "{\"platform\":\"coingecko\",\"author\":\"coingecko\",\"community\":\"pump-fun\",\"text\":\"LISTED Goatseus Maximus ($GOAT) rank=890\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1001000000,\"aggregator_listed\":true}",
    "{\"platform\":\"coingecko\",\"author\":\"coingecko\",\"community\":\"pump-fun\",\"text\":\"LISTED Peanut the Squirrel ($PNUT) rank=650\",\"likes\":0,\"reposts\":0,\"replies\":0,\"echo\":false,\"observed_at_ns\":1002000000,\"aggregator_listed\":true}",
];

#[test]
fn coingecko_trending_replay_is_byte_exact() {
    let out = run(&["coingecko", "--replay", &fixture("coingecko_trending.json")]);
    assert!(out.status.success(), "{out:?}");
    assert_eq!(
        stdout_lines(&out),
        COINGECKO_TRENDING_EXPECTED,
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 4 events"));
}

#[test]
fn coingecko_contract_replay_emits_listed_then_sentiment() {
    let out = run(&["coingecko", "--replay", &fixture("coingecko_contract.json")]);
    assert!(out.status.success(), "{out:?}");
    assert_eq!(
        stdout_lines(&out),
        COINGECKO_CONTRACT_EXPECTED,
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    // 3 polls: LISTED + SENTIMENT + one unchanged-gauge quiet poll.
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 2 events"));
}

#[test]
fn coingecko_markets_replay_labels_the_category() {
    let out = run(&[
        "coingecko",
        "--category",
        "pump-fun",
        "--replay",
        &fixture("coingecko_markets.json"),
    ]);
    assert!(out.status.success(), "{out:?}");
    assert_eq!(
        stdout_lines(&out),
        COINGECKO_MARKETS_EXPECTED,
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(String::from_utf8_lossy(&out.stderr).contains("replay: emitted 3 events"));
}

#[test]
fn coingecko_replay_is_deterministic_across_runs() {
    for f in [
        "coingecko_trending.json",
        "coingecko_contract.json",
        "coingecko_markets.json",
    ] {
        let a = run(&["coingecko", "--replay", &fixture(f)]);
        let b = run(&["coingecko", "--replay", &fixture(f)]);
        assert_eq!(a.stdout, b.stdout, "byte-identical replays for {f} (§22)");
        assert_eq!(a.stderr, b.stderr, "diagnostics deterministic for {f}");
    }
}

#[test]
fn coingecko_schema_drift_is_logged_and_survived() {
    let out = run(&["coingecko", "--replay", &fixture("coingecko_drift.json")]);
    assert!(
        out.status.success(),
        "drift must NOT kill the lane: {out:?}"
    );
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("SCHEMA_DRIFT trending: shape "),
        "drift is loud on stderr: {stderr}"
    );
    assert!(stderr.contains(" -> "), "old AND new hash logged: {stderr}");
    assert_eq!(
        stdout_lines(&out).len(),
        2,
        "the tolerant parser keeps emitting through the drift"
    );
}

#[test]
fn coingecko_without_mode_refuses_before_any_network() {
    let out = run(&["coingecko"]);
    assert_eq!(out.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&out.stderr).contains(
        "error: coingecko needs at least one mode: --trending | --category <id> | --contract-watch <mints-file>"
    ));
    assert!(out.stdout.is_empty(), "stdout stays NDJSON-only");
}

#[test]
fn coingecko_lines_round_trip_with_optional_field_order() {
    for f in [
        "coingecko_trending.json",
        "coingecko_contract.json",
        "coingecko_markets.json",
    ] {
        let out = run(&["coingecko", "--replay", &fixture(f)]);
        assert!(out.status.success(), "{f}");
        for line in stdout_lines(&out) {
            let v = json::parse(&line).unwrap_or_else(|e| panic!("invalid JSON {line:?}: {e}"));
            assert_eq!(json::serialize(&v), line, "round-trip drift in {f}");
            let json::Value::Object(pairs) = &v else {
                panic!("top level must be an object");
            };
            let keys: Vec<&str> = pairs.iter().map(|(k, _)| k.as_str()).collect();
            // The shared schema + capture stamp, then the optional coingecko
            // fields as an ORDER-PRESERVING SUBSET of the documented tail —
            // present only when the vendor stated them (§6.4).
            let base = [
                "platform",
                "author",
                "community",
                "text",
                "likes",
                "reposts",
                "replies",
                "echo",
                "observed_at_ns",
            ];
            assert_eq!(&keys[..9], &base, "{f}: fixed schema prefix");
            let tail = [
                "mint",
                "aggregator_listed",
                "sentiment_bp",
                "sentiment_conf_bp",
                "sentiment_model",
            ];
            let mut cursor = 0usize;
            for k in &keys[9..] {
                let pos = tail[cursor..]
                    .iter()
                    .position(|t| t == k)
                    .unwrap_or_else(|| panic!("{f}: unexpected/misordered tail key {k}"));
                cursor += pos + 1;
            }
            assert_eq!(pairs[0].1, json::Value::String("coingecko".to_string()));
            assert_eq!(pairs[1].1, json::Value::String("coingecko".to_string()));
            // sentiment_model appears iff sentiment_bp does (provenance tag).
            assert_eq!(
                keys.contains(&"sentiment_bp"),
                keys.contains(&"sentiment_model"),
                "{f}: model tag must accompany sentiment"
            );
        }
    }
}
