#!/usr/bin/env python3
"""Per-source rights determination for the North Star v2 corpus.

Gap B5 in the v2 plan. The rule this enforces: a source with no explicit,
rationalised rights basis is EXCLUDED, never included by default. Crucially it
also refuses the opposite failure mode -- a source may not be silently dropped
either. Every source the census sees must carry a determination.

This is an engineering determination with a stated basis and a named operator
authority. It is not legal advice, and it does not grant anything by itself.

  python3 rights_determination.py --census /training/v2/reports/SOURCE_RIGHTS_COVERAGE.json \
      --out /training/v2/contracts
"""
import argparse
import json
from pathlib import Path

SCHEMA = 'north_star_rights_determination_v1'

# class -> (basis, decision, rationale)
CLASSES = {
    'on_chain_public_ledger': (
        'Public permissionless blockchain data (Solana mainnet transactions, program '
        'events, account and token-balance state as recorded on-chain).',
        'INCLUDE',
        'Facts of a public ledger are not a copyrighted work and are recorded by the '
        'network rather than authored by a third party. Our extraction is a factual '
        'observation of that ledger. No terms-of-service counterparty is copied.'),
    'derived_computation': (
        'Values computed by our own code from public ledger observations (price series, '
        'prior-flow features, wallet position reconstruction, outcome arithmetic).',
        'INCLUDE',
        'Our own computational output over public factual inputs. We hold it and may '
        'train on it. Provenance is the producing code revision, which is pinned.'),
    'own_execution_data': (
        'Records of our own transactions, orders, fees, tips, failures and latencies.',
        'INCLUDE',
        'Generated by our operation; no third-party rights attach.'),
    'third_party_scraped_narrative': (
        'Content authored by third parties and retrieved from Telegram, X/Twitter, '
        'TikTok, Twitch, YouTube or general web (posts, captions, transcripts, pages).',
        'EXCLUDE',
        'Author-published content is protected and our retrieval establishes no licence. '
        'No grant exists for any of these sources. Under the standing data standard, '
        'unresolved rights means excluded. Re-entry requires a recorded grant per source '
        'naming the grantor, scope, and term.'),
    'third_party_code': (
        'Open-source repositories and binaries incorporated or referenced by the pipeline.',
        'INCLUDE_CONDITIONAL',
        'Usable under their own licences; the obligation is attribution and licence '
        'propagation, not training rights. Confirm each licence before redistribution.'),
    'base_model_weights': (
        'Upstream pretrained model weights used as the training seed.',
        'INCLUDE_CONDITIONAL',
        'Governed by the upstream licence shipped with the weights. Confirm the specific '
        'licence revision for the seed snapshot in use.'),
}

# Declared determinations. EVERY census source must appear or validation fails.
DETERMINATIONS = {
    'labels':      'on_chain_public_ledger',
    'roundtrips':  'derived_computation',
    'economics':   'derived_computation',
    'context':     'on_chain_public_ledger',
    'prices':      'derived_computation',
    'extract':     'on_chain_public_ledger',
    'anchor_econ': 'derived_computation',
    'recovered':   'derived_computation',
}

# Additional artefact families that are not sqlite sources in the census.
EXTRA = {
    'laserstream_capture': (
        'on_chain_public_ledger',
        'Raw program events observed from a public RPC feed. Note: the stored captures '
        'declare training_eligible=false and semantic_admission=false; eligibility must be '
        'revised explicitly by the operator before any training use, independently of rights.'),
    'narrative_spans_v1': (
        'third_party_scraped_narrative',
        'admitted_records=0; dominated by page chrome. Excluded.'),
    'twitch_transcripts': (
        'third_party_scraped_narrative', 'Excluded.'),
    'repo_code': ('third_party_code', ''),
    'qwen_seed_weights': ('base_model_weights', ''),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--census', type=Path,
                    default=Path('/training/v2/reports/SOURCE_RIGHTS_COVERAGE.json'))
    ap.add_argument('--out', type=Path, default=Path('/training/v2/contracts'))
    a = ap.parse_args()

    census = json.loads(a.census.read_text())
    census_sources = list(census['sources'].keys())

    entries = []
    missing = []
    for s in census_sources:
        cls = DETERMINATIONS.get(s)
        if cls is None:
            missing.append(s)
            continue
        basis, decision, rationale = CLASSES[cls]
        entries.append({'source': s, 'class': cls, 'rights_basis': basis,
                        'decision': decision, 'rationale': rationale,
                        'evidence_required': None if decision == 'INCLUDE' else
                        'recorded grant naming grantor, scope and term'})
    for s, (cls, note) in EXTRA.items():
        basis, decision, rationale = CLASSES[cls]
        entries.append({'source': s, 'class': cls, 'rights_basis': basis,
                        'decision': decision, 'rationale': rationale + (' ' + note if note else '').strip(),
                        'evidence_required': None if decision == 'INCLUDE' else
                        'recorded grant naming grantor, scope and term'})

    included = [e['source'] for e in entries if e['decision'] == 'INCLUDE']
    excluded = [e['source'] for e in entries if e['decision'].startswith('EXCLUDE')]

    doc = {
        'schema': SCHEMA,
        'determination_authority': 'operator (Alon)',
        'authored_by': 'agent',
        'scope_note': ('Engineering determination with stated basis, not legal advice. '
                       'Excluded sources are excluded; they are not provisionally included.'),
        'census_sources_covered': census_sources,
        'sources_without_determination': missing,
        'entries': entries,
        'included': included,
        'excluded': excluded,
        'complete': not missing,
    }
    a.out.mkdir(parents=True, exist_ok=True)
    (a.out / 'RIGHTS_DETERMINATION.v1.json').write_text(
        json.dumps(doc, indent=2) + '\n', encoding='utf-8')

    lines = ['# North Star v2 — Rights Determination (v1)', '',
             'Authority: operator. Authored by agent. Engineering determination with a '
             'stated basis, **not legal advice**.', '',
             'Rule: a source with no explicit rights basis is **excluded**, never included '
             'by default — and no census source may be silently dropped either.', '',
             '| Source | Class | Decision |', '|---|---|---|']
    for e in entries:
        lines.append(f"| `{e['source']}` | {e['class']} | **{e['decision']}** |")
    lines += ['', '## Rationales', '']
    seen = set()
    for e in entries:
        if e['class'] in seen:
            continue
        seen.add(e['class'])
        lines += [f"### {e['class']} — {e['decision']}", '', e['rationale'], '']
    if missing:
        lines += ['## INCOMPLETE', '', f'Sources lacking a determination: {missing}', '']
    (a.out / 'RIGHTS_DETERMINATION.v1.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')

    print(json.dumps({'complete': doc['complete'], 'missing': missing,
                      'included': included, 'excluded': excluded}, indent=2))
    if missing:
        raise SystemExit(2)


if __name__ == '__main__':
    main()