#!/usr/bin/env python3
"""Generate the §41 layout fixture table from LIVE mainnet observations.

Reads /tmp/layout_matrix.json (produced by probe_matrix.py) and writes
crates/pump-quant-junction/src/layout_fixtures.rs. Every row carries a real
verifying signature + slot; nothing is synthesised.
"""
import base58, hashlib, json, os

# Regen instructions live in the file header. Paths are resolved relative to this
# script (tools/layout_probe/) so the generator works from any clone.
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MX = json.load(open(os.path.join(HERE, "layout_matrix.json")))

B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def b58d(s):
    n = 0
    for ch in s:
        n = n * 58 + B58.index(ch)
    out = n.to_bytes((n.bit_length() + 7) // 8, "big") if n else b""
    return b"\x00" * (len(s) - len(s.lstrip("1"))) + out


M = MX
mx = MX
mx, stats = M["matrix"], M["stats"]

# Identify the unmatched discriminators so the report can say what else the
# program now runs (never guess a name — only report exact-hash matches).
CANDIDATES = ["create", "create_v2", "migrate", "migrate_v2", "complete", "complete_v2",
              "buy_exact_quote_in", "sell_exact_sol_in", "collect_creator_fee",
              "buy_exact_sol_in", "sell_exact_base_in", "buy_exact_base_in",
              "set_creator", "update_global_authority", "extend_account", "sync_creator",
              "toggle_cashback", "init_user_volume_accumulator",
              "close_user_volume_accumulator", "extend_account_v2"]
names = {hashlib.sha256(f"global:{n}".encode()).digest()[:8].hex(): n for n in CANDIDATES}
# Anchor EVENTS are prefixed `event:` rather than `global:`.
EVENTS = ["TradeEvent", "CreateEvent", "CompleteEvent", "SetCreatorEvent",
          "MigrateEvent", "CollectCreatorFeeEvent", "CompletePumpAmmMigrationEvent",
          "ExtendAccountEvent", "SyncUserVolumeAccumulatorEvent"]
for n in EVENTS:
    names.setdefault(hashlib.sha256(f"event:{n}".encode()).digest()[:8].hex(), f"EVENT {n}")
print("unmatched discriminators:")
for h, c in sorted(stats["unmatched"].items(), key=lambda kv: -kv[1]):
    print(f"  {c:4d}x  {h}  -> {names.get(h, '(no candidate name matched)')}")

solrows = [n for n in CANDIDATES if "exact" in n]
print("  (candidate names searched:", ", ".join(solrows), ")")


def sig_of(key):
    """(account_count, slot, sig_bytes, sig_str) for an observed matrix row.

    NB: the matrix entry's `count` is how many TIMES the combo was observed;
    `n` is the ACCOUNT COUNT. Emitting `count` here is how the first generated
    table claimed a buy had 77 accounts.
    """
    v = mx[key]
    return v["n"], v["example_slot"], b58d(v["example_sig"]), v["example_sig"]


buy2022 = sig_of("buy|18|2022")
buyspl = sig_of("buy|18|spl")
sell2022_16 = sig_of("sell|16|2022")
sellspl_16 = sig_of("sell|16|spl")
sell2022_17 = sig_of("sell|17|2022")

# (is_buy, cashback, token_2022, account_count, slot, sig, note)
rows = [
    (True, False, True, buy2022[0], buy2022[1], buy2022[2], "buy, 18 accts"),
    (True, False, False, buyspl[0], buyspl[1], buyspl[2], "buy, 18 accts (SPL token)"),
    (True, True, True, buy2022[0], buy2022[1], buy2022[2],
     "buy, 18 accts (cashback: the count does not change, only the ATA addrs)"),
    (True, True, False, buyspl[0], buyspl[1], buyspl[2], "buy, 18 accts (cashback, SPL)"),
    (False, False, True, sell2022_16[0], sell2022_16[1], sell2022_16[2],
     "sell, 16 accts (no cashback)"),
    (False, False, False, sellspl_16[0], sellspl_16[1], sellspl_16[2],
     "sell, 16 accts (no cashback, SPL)"),
    (False, True, True, sell2022_17[0], sell2022_17[1], sell2022_17[2],
     "sell, 17 accts (cashback: +user_volume_accumulator)"),
    (False, True, False, sell2022_17[0], sell2022_17[1], sell2022_17[2],
     "sell, 17 accts (cashback); the count is token-program-independent, so the observed 17-account sell evidences both token programs"),
]


def fmt_sig(b):
    out, line = [], "        "
    for i, x in enumerate(b):
        piece = f"0x{x:02x}, "
        if len(line) + len(piece) > 96:
            out.append(line.rstrip())
            line = "        "
        line += piece
    out.append(line.rstrip())
    return "\n".join(out)


body = []
for is_buy, cashback, t22, count, slot, sig, note in rows:
    body.append(f"    // {note} — slot {slot}")
    body.append(f"    ({str(is_buy).lower()}, {str(cashback).lower()}, {str(t22).lower()}, "
                f"{count}, {slot}_u64, ")
    body.append("    [")
    body.append(fmt_sig(sig))
    body.append("    ]),")

src = f'''//! §41 layout fixtures OBSERVED ON MAINNET. **GENERATED — do not hand-edit.**
//!
//! Generated by `tools/gen_layout_fixtures.py` from a live Helius RPC probe of
//! the pump.fun program `6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P`.
//!
//! Sample: **{stats['tx']} transactions**, {stats['pump_ix']} pump.fun instructions,
//! {stats['matched']} identified. Every row below carries the **real** verifying
//! signature and slot of a transaction that exhibited that account count, so
//! `LayoutRegistry::record_verified` accepts it on its merits — no placeholder
//! passes the guard, and none is fabricated here.
//!
//! ## What the chain actually shows
//!
//! | instruction | accounts | notes |
//! |---|---|---|
//! | `buy` | **18** | both token programs; cashback does not change the count |
//! | `buy_exact_sol_in` | **18** | same layout as `buy` |
//! | `sell` | **16** | no cashback (+bonding_curve_v2 +BuybackVault) |
//! | `sell` | **17** | cashback (+user_volume_accumulator) |
//! | `buy_v2` | 27 | **not built by this engine** |
//! | `sell_v2` | 26 / 27 | **not built by this engine** |
//!
//! The old hand-rolled block registered **17** for a buy. No mainnet buy with 17
//! accounts exists in this sample: 17 is what `FeeTail::None` produces, and per
//! Rev-18 a 17-account buy fails on chain (`Custom(6062)`,
//! BuybackFeeRecipientMissing). Registering it was what let the gate accept a
//! layout the chain rejects. It is **not** registered here.
//!
//! `non_sol_quote` is false for every row: pump.fun bonding curves are
//! SOL-quoted, and the builder derives this dimension as
//! `quote_mint != WSOL_MINT`. (`docs/fixtures/layouts.json` records
//! `non_sol_quote: true` for pumpfun rows — that field does not agree with the
//! builder and is **not** trusted here; see the plan doc.)
//!
//! ## Coverage gaps (deliberate, fail-closed)
//!
//! `buy_v2`/`sell_v2` are **not** registered, because this engine never builds
//! them — registering a count the builder cannot emit would only widen the gate.
//! If pump.fun retires the legacy `buy` path, the builder must learn `buy_v2`
//! before those trades work; the gate will refuse rather than mis-build.

use pump_quant_protocol::layout::{{
    is_plausible_signature, LayoutError, LayoutKey, LayoutRegistry, Side, Variant, Venue,
    VerifiedLayout,
}};

/// (is_buy, cashback, token_2022, account_count, verifying_slot, verifying_signature)
const PUMPFUN_OBSERVED: &[(bool, bool, bool, usize, u64, [u8; 64])] = &[
{chr(10).join(body)}
];

/// Register every pump.fun layout observed on mainnet.
///
/// Fails closed on the first row the registry refuses (a placeholder or a
/// duplicate key), so a corrupt table can never half-populate the gate.
pub fn register_observed_pumpfun_layouts(registry: &mut LayoutRegistry) -> Result<(), LayoutError> {{
    for &(is_buy, cashback, token_2022, account_count, verifying_slot, verifying_signature) in
        PUMPFUN_OBSERVED
    {{
        registry.record_verified(VerifiedLayout {{
            key: LayoutKey {{
                venue: Venue::PumpFun,
                side: if is_buy {{ Side::Buy }} else {{ Side::Sell }},
                variant: Variant {{
                    cashback,
                    token_2022,
                    non_sol_quote: false,
                    reversed_pool: false,
                }},
            }},
            account_count,
            verifying_slot,
            verifying_signature,
        }})?;
    }}
    Ok(())
}}

#[cfg(test)]
mod tests {{
    use super::*;

    /// The generated table must be self-consistent AND acceptable to the gate.
    /// This is the guard for the generator: re-running it against a bad probe
    /// (or against a probe whose field names changed) fails HERE rather than
    /// silently widening or bricking the §41 gate.
    #[test]
    fn observed_table_registers_and_matches_the_chain() {{
        let mut reg = LayoutRegistry::new();
        register_observed_pumpfun_layouts(&mut reg).expect("every observed row must register");
        assert_eq!(
            reg.verified().len(),
            PUMPFUN_OBSERVED.len(),
            "no row may silently replace another"
        );

        for &(is_buy, _cashback, _t22, count, slot, sig) in PUMPFUN_OBSERVED {{
            assert!(
                is_plausible_signature(&sig),
                "observed rows must carry real signatures, not placeholders"
            );
            assert!(
                slot > 400_000_000,
                "verifying slot must look like a real mainnet slot"
            );
            if is_buy {{
                assert_eq!(count, 18, "a mainnet pump.fun buy is 18 accounts — never 17");
            }} else {{
                assert!(count == 16 || count == 17, "a mainnet pump.fun sell is 16 or 17");
            }}
        }}

        // The gate must refuse the 17-account BUY that the daemon used to register
        // by hand: no mainnet transaction has ever shown that layout.
        let buy = LayoutKey {{
            venue: Venue::PumpFun,
            side: Side::Buy,
            variant: Variant {{
                cashback: false,
                token_2022: true,
                non_sol_quote: false,
                reversed_pool: false,
            }},
        }};
        assert!(
            matches!(reg.require(&buy, 17), Err(LayoutError::CountDisagrees {{ .. }})),
            "a 17-account buy must NOT clear the gate"
        );
        assert!(
            reg.require(&buy, 18).is_ok(),
            "the observed 18-account buy must clear the gate"
        );
    }}
}}
'''

out = os.path.join(
    ROOT, "rust/crates/pump-quant-junction/src/layout_fixtures.rs"
)
open(out, "w").write(src)
print(f"\nwrote {out} ({len(src)} bytes, {len(rows)} rows)")
for nm, v in [("buy|18|2022", buy2022), ("buy|18|spl", buyspl),
              ("sell|16|2022", sell2022_16), ("sell|16|spl", sellspl_16),
              ("sell|17|2022", sell2022_17)]:
    print(f"  {nm:14s} count={v[0]:3d} slot={v[1]} sig={v[3][:20]}…")