#!/usr/bin/env python3
"""
regression_e2e.py — the single authoritative END-TO-END regression runner for the
whole Hermes repo. Exercises the repository the way a fresh clone + CI would and
asserts every pinned invariant, exiting NON-ZERO on any drift.

WHAT IT RUNS (in order; each contributes rows to the final invariant table)
  (a) Rust workspace gate — `cargo fmt --check`, `cargo clippy -D warnings`,
      `cargo test --workspace`. If QA-1's `pq-regression` crate is present it is
      ALSO run (`cargo test -p pq-regression`) as the durable golden-tape /
      fail-closed tripwire. The Rust digest / net-SOL / promoted-admitted-rejected
      counts are QA-1's manifest (rust/crates/pq-regression/src/baselines.rs +
      BASELINES.md) — this runner REFERENCES that manifest and asserts the gate is
      green; it does not duplicate those numbers.
  (b) Each capture suite's tests, asserting the test count does not DROP below the
      pinned floor:  stream-capture-rs, social-ingest-https-rs, social-ingest-rs.
  (c) scripts/ci_gate.py --repo .   → must print the portable gate PASSED.
  (d) scripts/materialize_tests.py --repo . --verify → must report the pinned
      dossier count intact and unmodified.
  (e) The supervisor Python test suite (stdlib unittest) → must be OK.
  (f) Supervisor term-set sizes (§45.1 status enum, §56.10 inference ladder,
      §56.5 root-cause taxonomy) surfaced directly so a silent shrink shows in
      the table.

VENDORED-BUILD CONVENTION (why the capture suites can build offline here)
  crates.io is unreachable in this sandbox. Each Rust crate resolves its pinned
  dependency tree against a LOCAL vendored copy at /tmp/vw/vendor via an
  UNCOMMITTED `.cargo/config.toml` ([source.crates-io] replace-with =
  "vendored-sources"). This runner WRITES that config into any capture suite that
  lacks it (pointing at --vendor-dir) so the offline build just works, and removes
  only the configs it created. It never commits `.cargo/` or the vendor tree.

FRESH-CLONE REQUIREMENTS (NOT in the repo — see REGRESSION_BASELINES.md)
  A fresh clone has neither the vendor tree nor a populated Cargo registry. To run
  this end-to-end you need ONE of:
    * network access to the real crates.io (delete/skip the vendored `.cargo`
      configs and let cargo fetch), OR
    * the vendored tree reconstructed at the path given by --vendor-dir (default
      /tmp/vw/vendor), e.g. via `cargo vendor` on a networked machine copied in.
  The rust/ workspace itself has NO external registry dependencies and builds with
  neither. Live capture (not tested here) additionally needs the per-lane API keys
  documented in each suite's README; every lane is fail-closed without them.

Deterministic and CI-friendly: no wall-clock in any assertion, no network. Runtime
is dominated by cargo compilation on a cold target; a warm target is seconds.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

# ------------------------------------------------------------------ config

VENDOR_DEFAULT = "/tmp/vw/vendor"

# Pinned capture-suite test-count FLOORS (this runner owns these). The spec's
# pre-hardening baselines were stream=122 / https=183 / twitch=23; the additive
# regression-hardening in tests/regression_*.rs raised the first two. The floor is
# the CURRENT hardened total, so removing either the base OR the hardening trips
# the gate. Growth (more tests) is always allowed (comparator is >=).
CAPTURE_SUITES = [
    # (dir under tools/, cargo package, pinned floor, pre-hardening spec baseline)
    ("stream-capture-rs", "pq-stream-capture", 134, 122),
    ("social-ingest-https-rs", "pq-social-capture", 191, 183),
    ("social-ingest-rs", "pq-twitch-capture", 23, 23),
]

# The vendored-build config written into a capture suite that lacks one.
CARGO_CONFIG_TEMPLATE = (
    "# GENERATED by scripts/regression_e2e.py — UNCOMMITTED build-sandbox config.\n"
    "# crates.io is unreachable in this sandbox; resolve against the local vendored\n"
    "# tree. Never commit this file or the vendor directory.\n"
    "[source.crates-io]\n"
    "replace-with = \"vendored-sources\"\n\n"
    "[source.vendored-sources]\n"
    "directory = \"{vendor}\"\n"
)

DOSSIER_BASELINE = 191
TAXONOMY_BASELINE = 50
SEEDED_STATES_BASELINE = 7
INFERENCE_STATES_BASELINE = 7
SUPERVISOR_TESTS_BASELINE = 51

_TEST_OK_RE = re.compile(r"test result: ok\. (\d+) passed")
_TEST_ANY_RE = re.compile(r"test result: \w+\. (\d+) passed")


# ------------------------------------------------------------------ model

@dataclass
class Invariant:
    category: str
    name: str
    comparator: str            # "==", ">=", or "pass"
    baseline: object           # expected value / floor, or None for pass/fail
    observed: object           # observed value, or True/False for pass/fail
    ok: bool
    note: str = ""


@dataclass
class Runner:
    repo: Path
    vendor: str
    skip_rust: bool
    invariants: list[Invariant] = field(default_factory=list)
    created_configs: list[Path] = field(default_factory=list)
    t0: float = field(default_factory=time.monotonic)

    # -- process helper -----------------------------------------------------
    def _run(self, cmd: list[str], cwd: Optional[Path] = None,
             timeout: int = 3600) -> subprocess.CompletedProcess:
        print(f"  $ {' '.join(cmd)}  (cwd={cwd or self.repo})", flush=True)
        return subprocess.run(
            cmd, cwd=str(cwd or self.repo), capture_output=True, text=True,
            timeout=timeout,
        )

    @staticmethod
    def _sum_passed(stdout: str) -> int:
        return sum(int(m) for m in _TEST_OK_RE.findall(stdout))

    def _add(self, inv: Invariant) -> None:
        self.invariants.append(inv)
        mark = "PASS" if inv.ok else "FAIL"
        print(f"    [{mark}] {inv.category}: {inv.name} "
              f"(observed={inv.observed} {inv.comparator} baseline={inv.baseline})",
              flush=True)

    # -- vendored config ----------------------------------------------------
    def ensure_vendored_config(self, suite_dir: Path) -> None:
        # Only write a vendored config if the vendor tree actually exists;
        # otherwise an online build (no --offline) needs the default crates.io
        # source, and a stale vendored config pointing at a missing dir breaks it.
        if not Path(self.vendor).is_dir():
            return
        cfg = suite_dir / ".cargo" / "config.toml"
        if cfg.exists():
            return
        cfg.parent.mkdir(parents=True, exist_ok=True)
        cfg.write_text(CARGO_CONFIG_TEMPLATE.format(vendor=self.vendor), encoding="utf-8")
        self.created_configs.append(cfg)
        print(f"    wrote temporary vendored config: {cfg}", flush=True)

    def cleanup_configs(self) -> None:
        for cfg in self.created_configs:
            try:
                cfg.unlink()
                # prune an empty .cargo dir we created
                parent = cfg.parent
                if parent.name == ".cargo" and not any(parent.iterdir()):
                    parent.rmdir()
            except OSError:
                pass

    # -- (a) rust workspace gate -------------------------------------------
    def rust_gate(self) -> None:
        print("\n== (a) Rust workspace gate ==", flush=True)
        rust = self.repo / "rust"
        if self.skip_rust:
            self._add(Invariant("rust", "workspace gate", "pass", "run",
                                 "skipped", False, "--skip-rust set; NOT a green run"))
            return
        if not (rust / "Cargo.toml").is_file():
            self._add(Invariant("rust", "workspace present", "pass", True, False, False,
                                 "rust/Cargo.toml missing"))
            return

        # fmt --check (fast, no compile)
        # On Windows, `cargo fmt --all --check` hits OS error 206
        # (ERROR_FILENAME_EXCED_RANGE) when workspace paths exceed MAX_PATH.
        # Fall back to per-crate checks, which work because each crate path
        # is shorter.
        r = self._run(["cargo", "fmt", "--all", "--check"], cwd=rust, timeout=600)
        if r.returncode != 0 and sys.platform == "win32" \
                and ("error 206" in (r.stdout + r.stderr).lower()
                     or "too long" in (r.stdout + r.stderr).lower()):
            # Per-crate fallback
            import re as _re
            manifest = (rust / "Cargo.toml").read_text(encoding="utf-8")
            members = []
            m = _re.search(r"members\s*=\s*\[(.*?)\]", manifest, _re.DOTALL)
            if m:
                for item in _re.findall(r'"([^"]+)"', m.group(1)):
                    if "*" in item:
                        base = rust / item.replace("/*", "")
                        if base.is_dir():
                            for sub in base.iterdir():
                                if (sub / "Cargo.toml").is_file():
                                    members.append(sub.name)
                    else:
                        members.append(item)
            fmt_fail = False
            for crate in members:
                rc = self._run(["cargo", "fmt", "-p", crate, "--check"],
                              cwd=rust, timeout=120)
                if rc.returncode != 0:
                    fmt_fail = True
                    break
            r = subprocess.CompletedProcess(
                ["cargo", "fmt", "--per-crate"], 0 if not fmt_fail else 1,
                f"per-crate fmt check: {'clean' if not fmt_fail else 'DIFF'}",
                "")
        self._add(Invariant("rust", "cargo fmt --check", "pass", "clean",
                            "clean" if r.returncode == 0 else "DIFF", r.returncode == 0,
                            "" if r.returncode == 0 else r.stdout[-400:]))

        # clippy -D warnings (all targets)
        r = self._run(["cargo", "clippy", "--workspace", "--all-targets", "--offline",
                       "--", "-D", "warnings"], cwd=rust, timeout=3600)
        self._add(Invariant("rust", "cargo clippy -D warnings", "pass", "clean",
                            "clean" if r.returncode == 0 else "WARN/ERR", r.returncode == 0,
                            "" if r.returncode == 0 else _tail(r)))

        # cargo test --workspace
        r = self._run(["cargo", "test", "--workspace", "--offline"], cwd=rust, timeout=3600)
        count = self._sum_passed(r.stdout)
        self._add(Invariant("rust", "cargo test --workspace", "pass",
                            "all pass", f"{count} passed" if r.returncode == 0 else "FAILED",
                            r.returncode == 0, "" if r.returncode == 0 else _tail(r)))

        # QA-1's pq-regression crate (golden-tape / fail-closed tripwire) if present
        pq_reg = rust / "crates" / "pq-regression"
        if pq_reg.is_dir():
            r = self._run(["cargo", "test", "-p", "pq-regression", "--offline"],
                          cwd=rust, timeout=3600)
            count = self._sum_passed(r.stdout)
            manifest = "rust/crates/pq-regression/src/baselines.rs"
            self._add(Invariant("rust", "pq-regression crate (QA-1 manifest)", "pass",
                                "all pass", f"{count} passed" if r.returncode == 0 else "FAILED",
                                r.returncode == 0,
                                f"digest/net/counts pinned in {manifest} (QA-1-owned)"
                                if r.returncode == 0 else _tail(r)))
        else:
            self._add(Invariant("rust", "pq-regression crate", "pass", "present-or-absent",
                                "absent", True,
                                "QA-1's crate not yet in tree; workspace gate stands in"))

    # -- (b) capture suites -------------------------------------------------
    def capture_suites(self) -> None:
        print("\n== (b) Capture suites ==", flush=True)
        for suite, _pkg, floor, spec in CAPTURE_SUITES:
            suite_dir = self.repo / "tools" / suite
            if not (suite_dir / "Cargo.toml").is_file():
                self._add(Invariant("capture", f"{suite} present", ">=", floor, "MISSING",
                                    False, "suite directory missing"))
                continue
            self.ensure_vendored_config(suite_dir)
            # Use --offline only when the vendor tree exists; otherwise let cargo
            # fetch from crates.io (the lockfile must be resolvable online).
            offline_args = ["--offline"] if Path(self.vendor).is_dir() else []
            r = self._run(["cargo", "test", *offline_args], cwd=suite_dir, timeout=3600)
            if r.returncode != 0:
                self._add(Invariant("capture", f"{suite} tests", ">=", floor, "FAILED",
                                    False, _tail(r)))
                continue
            count = self._sum_passed(r.stdout)
            self._add(Invariant("capture", f"{suite} tests", ">=", floor, count,
                                count >= floor,
                                f"pre-hardening spec baseline {spec}"))

    # -- (c) ci_gate --------------------------------------------------------
    def ci_gate(self) -> None:
        print("\n== (c) ci_gate.py ==", flush=True)
        r = self._run([sys.executable, "scripts/ci_gate.py", "--repo", "."], timeout=600)
        passed = r.returncode == 0 and "portable gate PASSED" in r.stdout
        self._add(Invariant("gate", "ci_gate.py --repo .", "pass", "PASSED",
                            "PASSED" if passed else "FAILED", passed,
                            "" if passed else _tail(r)))
        # The hot-path lint is now LIVE over the app crates: assert ci_gate reports
        # NON-ZERO hot/money globs (i.e. real crates were matched, not an empty
        # scope that would make the lint vacuously "clean"). Parse the emitted
        # "hot=<n> money=<m>" scope line.
        m = re.search(r"hot-path lint \(hot=(\d+) money=(\d+)", r.stdout)
        if m:
            hot_n, money_n = int(m.group(1)), int(m.group(2))
            nonzero = hot_n > 0 and money_n > 0
            self._add(Invariant("gate", "hot-path lint globs non-empty", ">=", "hot>=1,money>=1",
                                f"hot={hot_n},money={money_n}", nonzero,
                                "lint scope must match real app crates, not zero"))
        else:
            self._add(Invariant("gate", "hot-path lint globs non-empty", ">=", "hot>=1,money>=1",
                                "no scope line", False,
                                "ci_gate did not report a hot/money glob scope"))

    # -- (d) materialize verify --------------------------------------------
    def materialize_verify(self) -> None:
        print("\n== (d) materialize_tests.py --verify ==", flush=True)
        r = self._run([sys.executable, "scripts/materialize_tests.py", "--repo", ".",
                       "--verify"], timeout=600)
        m = re.search(r"OK — (\d+) dossier tests intact", r.stdout)
        count = int(m.group(1)) if m else -1
        ok = r.returncode == 0 and count == DOSSIER_BASELINE
        self._add(Invariant("gate", "materialized dossier tests", "==", DOSSIER_BASELINE,
                            count if count >= 0 else "FAILED", ok,
                            "" if ok else _tail(r)))

    # -- (e) supervisor python tests ---------------------------------------
    def supervisor_tests(self) -> None:
        print("\n== (e) supervisor Python tests ==", flush=True)
        r = self._run([sys.executable, "-m", "unittest", "discover", "-s",
                       "supervisor/tests", "-t", "."], timeout=900)
        # unittest prints "Ran N tests" and "OK" to stderr
        blob = r.stdout + r.stderr
        m = re.search(r"Ran (\d+) tests", blob)
        count = int(m.group(1)) if m else -1
        ok = r.returncode == 0 and count >= SUPERVISOR_TESTS_BASELINE
        self._add(Invariant("supervisor", "unittest suite", ">=", SUPERVISOR_TESTS_BASELINE,
                            count if count >= 0 else "FAILED", ok,
                            "" if ok else blob[-400:]))

    # -- (f) supervisor term sets ------------------------------------------
    def supervisor_term_sets(self) -> None:
        print("\n== (f) supervisor term-set sizes ==", flush=True)
        if str(self.repo) not in sys.path:
            sys.path.insert(0, str(self.repo))
        try:
            from supervisor.analysis.root_cause import ROOT_CAUSE_CLASSES
            from supervisor.store.evidence import (
                SEEDED_FINDING_STATES, VALID_INFERENCE_STATES,
            )
        except Exception as e:  # noqa: BLE001
            self._add(Invariant("supervisor", "import term sets", "pass", True, False,
                                False, f"import error: {e}"))
            return
        n_tax = len(ROOT_CAUSE_CLASSES)
        self._add(Invariant("supervisor", "§56.5 root-cause taxonomy", ">=",
                            TAXONOMY_BASELINE, n_tax, n_tax >= TAXONOMY_BASELINE
                            and len(set(ROOT_CAUSE_CLASSES)) == n_tax))
        n_seed = len(SEEDED_FINDING_STATES)
        self._add(Invariant("supervisor", "§45.1 evidence-status enum", ">=",
                            SEEDED_STATES_BASELINE, n_seed, n_seed >= SEEDED_STATES_BASELINE))
        n_inf = len(VALID_INFERENCE_STATES)
        self._add(Invariant("supervisor", "§56.10 inference ladder", ">=",
                            INFERENCE_STATES_BASELINE, n_inf, n_inf >= INFERENCE_STATES_BASELINE))

    # -- orchestration ------------------------------------------------------
    def run(self) -> int:
        print(f"regression_e2e over {self.repo}  (vendor={self.vendor})", flush=True)
        try:
            self.rust_gate()
            self.capture_suites()
            self.ci_gate()
            self.materialize_verify()
            self.supervisor_tests()
            self.supervisor_term_sets()
        finally:
            self.cleanup_configs()
        return self.summarize()

    def summarize(self) -> int:
        elapsed = time.monotonic() - self.t0
        failures = [i for i in self.invariants if not i.ok]
        print("\n" + "=" * 78)
        print("REGRESSION E2E — INVARIANT SUMMARY")
        print("=" * 78)
        hdr = f"{'STATUS':6} {'CATEGORY':11} {'INVARIANT':38} {'OBSERVED':>12} {'BASE':>8}"
        print(hdr)
        print("-" * 78)
        for i in self.invariants:
            obs = str(i.observed)
            base = str(i.baseline)
            print(f"{'PASS' if i.ok else 'FAIL':6} {i.category:11} "
                  f"{i.name[:38]:38} {obs[:12]:>12} {base[:8]:>8}")
        print("-" * 78)
        print(f"{len(self.invariants)} invariants, {len(failures)} failing, "
              f"runtime {elapsed:.1f}s")
        if failures:
            print("\nFAILING INVARIANTS (detail):")
            for i in failures:
                print(f"  * {i.category}/{i.name}: observed={i.observed} "
                      f"{i.comparator} baseline={i.baseline}")
                if i.note:
                    print(f"      {i.note.strip()[:600]}")
            print("\nREGRESSION E2E: FAIL")
            return 1
        print("\nREGRESSION E2E: PASS — every pinned invariant holds.")
        return 0


def _tail(proc: subprocess.CompletedProcess) -> str:
    return (proc.stdout[-500:] + "\n" + proc.stderr[-500:]).strip()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=str(Path(__file__).resolve().parent.parent),
                    help="repo root (default: this script's parent's parent)")
    ap.add_argument("--vendor-dir", default=VENDOR_DEFAULT,
                    help=f"vendored crates.io tree (default {VENDOR_DEFAULT})")
    ap.add_argument("--skip-rust", action="store_true",
                    help="skip the Rust workspace gate (for a Python-only CI stage; the "
                         "resulting run is NOT a full green and is marked FAIL)")
    args = ap.parse_args()

    repo = Path(args.repo).resolve()
    if not (repo / "supervisor").is_dir():
        print(f"[regression_e2e] {repo} does not look like the Hermes repo")
        return 2
    if not Path(args.vendor_dir).is_dir():
        print(f"[regression_e2e] WARNING: vendor dir {args.vendor_dir} not found — capture-suite "
              f"builds will fail unless crates.io is reachable. See REGRESSION_BASELINES.md.")
    return Runner(repo=repo, vendor=args.vendor_dir, skip_rust=args.skip_rust).run()


if __name__ == "__main__":
    raise SystemExit(main())
